# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\GuiTest.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import uic
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import ( 
    QApplication, QMainWindow, QPushButton, QLabel, QFileDialog,
    QTableWidget, QTableWidgetItem, QHeaderView,QLineEdit, QCheckBox,
    QWidget, QMessageBox, QComboBox
 )
from PyQt5.QtGui import QDoubleValidator, QIntValidator, QRegularExpressionValidator
from PyQt5.QtCore import QRegularExpression
import sys
from pathlib import Path
import os
import numpy as np 
import trimesh
from skimage import measure, filters, morphology
import imageio
import random
import tifffile as tiff
import itertools
from scipy.spatial import ConvexHull
from collections import defaultdict
import multiprocessing
import os
from scipy.ndimage import distance_transform_edt
from skimage.feature import peak_local_max
import re
import json
import networkx as nx

class UI(QMainWindow):
    def __init__(self):
        super(UI,self).__init__()
        
        uic.loadUi('HERMESGUI.ui',self)
        

        # Create delete button
        self.AddButton = self.findChild(QPushButton, 'AddButton')
        self.AddButton.clicked.connect(lambda: self.add_manual_entry(self.manualInput,self.tableWidget))
        
        # Set up Manual Name
        self.manualInput = self.findChild(QLineEdit, 'FileNamelineEdit')
        self.manualInput.setPlaceholderText("Enter file name manually...")
        
        # Set up find Menue
        self.FindButton = self.findChild(QPushButton, 'FindButton')
        self.FindButton.clicked.connect(self.open_file_dialog)
        
        # Set up table properties
        self.tableWidget = self.findChild(QTableWidget, 'FileNamestableWidget')
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setHorizontalHeaderLabels(["File Name", "Voxel Size"])
        self.tableWidget.setColumnWidth(0, 250)  # Adjust column width
        self.tableWidget.setColumnWidth(1, 100)
        self.tableWidget.setSelectionBehavior(QTableWidget.SelectRows)  # Select entire rows
        self.tableWidget.setSelectionMode(QTableWidget.ExtendedSelection)  # Allow selecting one row at a time
        self.tableWidget.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        
        # Create delete button
        self.DeleteButton = self.findChild(QPushButton, 'DeleteButton')
        self.DeleteButton.clicked.connect(lambda: self.delete_selected_rows(self.tableWidget))
        
        # Set a QDoubleValidator to only allow floating-point numbers
        float_validator = QDoubleValidator()
        float_validator.setRange(0, 999999, 5)
        float_validator.setNotation(QDoubleValidator.StandardNotation)  # Allows standard float notation
        
        int_validator = self.int_validator = QIntValidator(0, 99999999)
        
        # Set up Laplacian Filter
        self.LaplaciancheckBox = self.findChild(QCheckBox, 'LaplaciancheckBox')
        self.LaplacianItertextEdit = self.findChild(QLineEdit, 'LaplacianItertextEdit')
        self.LaplacianItertextEdit.setValidator(int_validator)
        
        # Initially disable the line edit if the checkbox is not checked
        self.LaplacianItertextEdit.setEnabled(self.LaplaciancheckBox.isChecked())
        
        # Connect the checkbox state change to a function
        self.LaplaciancheckBox.stateChanged.connect(lambda: self.toggle_widgets(self.LaplaciancheckBox, [self.LaplacianItertextEdit]))
        
        # Set up Laplacian Filter
        self.ScreenedPoissoncheckBox = self.findChild(QCheckBox, 'ScreenedPoissoncheckBox')
        self.ScreenedPoissonItertextEdit = self.findChild(QLineEdit, 'ScreenedPoissonItertextEdit')
        self.ScreenedPoissonItertextEdit.setValidator(int_validator)
        
        # Initially disable the line edit if the checkbox is not checked
        self.ScreenedPoissonItertextEdit.setEnabled(self.ScreenedPoissoncheckBox.isChecked())
        
        # Connect the checkbox state change to a function
        self.ScreenedPoissoncheckBox.stateChanged.connect(lambda: self.toggle_widgets(self.ScreenedPoissoncheckBox, [self.ScreenedPoissonItertextEdit]))
        
        self.RemoveIslandscheckBox = self.findChild(QCheckBox, 'RemoveIslandscheckBox')
        
        # Set up Regular inputs
        self.VolumnLengthlineEdit = self.findChild(QLineEdit, 'VolumnLengthlineEdit')
        self.VolumnLengthlineEdit.setValidator(int_validator)
        
        self.VolumnNumberlineEdit = self.findChild(QLineEdit, 'VolumnNumberlineEdit')
        self.VolumnNumberlineEdit.setValidator(int_validator)
        
        # Set up Corners inputs
        self.VolumnLengthCornerlineEdit = self.findChild(QLineEdit, 'VolumnLengthCornerlineEdit')
        self.VolumnLengthCornerlineEdit.setValidator(int_validator)
        
        # Create delete button
        self.AddCornerButton = self.findChild(QPushButton, 'AddCornerButton')
        self.AddCornerButton.clicked.connect(lambda: self.add_manual_entry(self.CornerlineEdit,self.CornertableWidget))
        
        # Set up Manual Name
        self.CornerlineEdit = self.findChild(QLineEdit, 'CornerlineEdit')
        self.CornerlineEdit.setPlaceholderText("x_coord., y_coord., z_coord. (voxel)")
        # Regular expression for three integers separated by commas (spaces allowed)
        regex = QRegularExpression(r"^\d+,\d+,\d+$")
        validator = QRegularExpressionValidator(regex)
        self.CornerlineEdit.setValidator(validator)
        
        self.FindCornerButton = self.findChild(QPushButton, 'FindCornerButton')
        self.FindCornerButton.clicked.connect(self.add_corner_data)
        
        self.CornertableWidget = self.findChild(QTableWidget, 'CornertableWidget')
        self.CornertableWidget.setColumnCount(3)
        self.CornertableWidget.setHorizontalHeaderLabels(["x coord.", "y coord.", "z coord.",])
        self.CornertableWidget.setColumnWidth(0, 100)
        self.CornertableWidget.setColumnWidth(1, 100)
        self.CornertableWidget.setColumnWidth(2, 100)
        self.CornertableWidget.setSelectionBehavior(QTableWidget.SelectRows)  # Select entire rows
        self.CornertableWidget.setSelectionMode(QTableWidget.ExtendedSelection)  # Allow selecting one row at a time
        self.CornertableWidget.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        
        # Create delete button
        self.DeleteCornerButton = self.findChild(QPushButton, 'DeleteCornerButton')
        self.DeleteCornerButton.clicked.connect(lambda: self.delete_selected_rows(self.CornertableWidget))
        
        # Set up Save Options
        self.TiffSavecheckBox = self.findChild(QCheckBox, 'TiffSavecheckBox')
        self.TiffSavePathtextEdit = self.findChild(QLineEdit, 'TiffSavePathtextEdit')
        
        # Initially disable the line edit if the checkbox is not checked
        self.TiffSavePathtextEdit.setEnabled(self.TiffSavecheckBox.isChecked())
        
        # Connect the checkbox state change to a function
        self.TiffSavecheckBox.stateChanged.connect(lambda: self.toggle_widgets(self.TiffSavecheckBox, [self.TiffSavePathtextEdit]))
        
        # Set up Save Options
        self.VoxelSavePathcheckBox = self.findChild(QCheckBox, 'VoxelSavePathcheckBox')
        self.VoxelSavePathtextEdit = self.findChild(QLineEdit, 'VoxelSavePathtextEdit')
        
        # Initially disable the line edit if the checkbox is not checked
        self.VoxelSavePathtextEdit.setEnabled(self.VoxelSavePathcheckBox.isChecked())
        
        # Connect the checkbox state change to a function
        self.VoxelSavePathcheckBox.stateChanged.connect(lambda: self.toggle_widgets(self.VoxelSavePathcheckBox, [self.VoxelSavePathtextEdit]))
        
        # Set up Laplacian Filter
        self.StlSavePathcheckBox = self.findChild(QCheckBox, 'StlSavePathcheckBox')
        self.StlSavePathtextEdit = self.findChild(QLineEdit, 'StlSavePathtextEdit')
        
        # Initially disable the line edit if the checkbox is not checked
        self.StlSavePathtextEdit.setEnabled(self.StlSavePathcheckBox.isChecked())
        
        # Connect the checkbox state change to a function
        self.StlSavePathcheckBox.stateChanged.connect(lambda: self.toggle_widgets(self.StlSavePathcheckBox, [self.StlSavePathtextEdit]))
        
        # Set up Properties flags
        self.PropertySavecheckBox = self.findChild(QCheckBox, 'PropertySavecheckBox')
        self.PropertySavePathtextEdit = self.findChild(QLineEdit, 'PropertySavePathtextEdit')
        self.MinMaxcheckBox = self.findChild(QCheckBox, 'MinMaxcheckBox')
        self.SurfAreacheckBox = self.findChild(QCheckBox, 'SurfAreacheckBox')
        self.ClosedVolumecheckBox = self.findChild(QCheckBox, 'ClosedVolumecheckBox')
        self.VolbyAreacheckBox = self.findChild(QCheckBox, 'VolbyAreacheckBox')
        self.PorositycheckBox = self.findChild(QCheckBox, 'PorositycheckBox')
        self.FiberDiametercheckBox = self.findChild(QCheckBox, 'FiberDiametercheckBox')
        self.FiberDiamSpherelineEdit = self.findChild(QLineEdit, 'FiberDiamSpherelineEdit')
        self.FiberDiamSpherelineEdit.setValidator(float_validator)
        self.PoreDistributioncheckBox = self.findChild(QCheckBox, 'PoreDistributioncheckBox')
        self.PoreDistSpherelineEdit = self.findChild(QLineEdit, 'PoreDistSpherelineEdit')
        self.PoreDistSpherelineEdit.setValidator(float_validator)
        self.FiberAnglecheckBox = self.findChild(QCheckBox, 'FiberAnglecheckBox') 
        self.PlaneAnglecomboBox = self.findChild(QComboBox, 'PlaneAnglecomboBox')
        self.FiberLengthcheckBox = self.findChild(QCheckBox, 'FiberLengthcheckBox')
        
        initialStat = self.PropertySavecheckBox.isChecked()
        
        # Initially disable the line edit if the checkbox is not checked
        self.PropertySavePathtextEdit.setEnabled(initialStat)
        self.MinMaxcheckBox.setEnabled(initialStat)
        self.SurfAreacheckBox.setEnabled(initialStat)
        self.ClosedVolumecheckBox.setEnabled(initialStat)
        self.VolbyAreacheckBox.setEnabled(initialStat)
        self.PorositycheckBox.setEnabled(initialStat)
        self.FiberDiametercheckBox.setEnabled(initialStat)
        self.FiberDiamSpherelineEdit.setEnabled(initialStat)
        self.PoreDistributioncheckBox.setEnabled(initialStat)
        self.PoreDistSpherelineEdit.setEnabled(initialStat)
        self.FiberAnglecheckBox.setEnabled(initialStat)
        self.PlaneAnglecomboBox.setEnabled(initialStat)
        self.FiberLengthcheckBox.setEnabled(initialStat)
        
        self.FiberDiamSpherelineEdit.setEnabled(self.FiberDiametercheckBox.isChecked())
        self.FiberDiametercheckBox.stateChanged.connect(lambda: self.toggle_widgets(self.FiberDiametercheckBox,
                                                                                   [self.FiberDiamSpherelineEdit]))
        
        self.PoreDistSpherelineEdit.setEnabled(self.PoreDistributioncheckBox.isChecked())
        self.PoreDistributioncheckBox.stateChanged.connect(lambda: self.toggle_widgets(self.PoreDistributioncheckBox,
                                                                                   [self.PoreDistSpherelineEdit]))
        
        self.PlaneAnglecomboBox.setEnabled(self.FiberAnglecheckBox.isChecked())
        self.FiberAnglecheckBox.stateChanged.connect(lambda: self.toggle_widgets(self.FiberAnglecheckBox,
                                                                                   [self.PlaneAnglecomboBox]))
        
        # Connect the checkbox state change to a function
        self.PropertySavecheckBox.stateChanged.connect(lambda: self.toggle_widgets(self.PropertySavecheckBox,
                                                                                   [self.PropertySavePathtextEdit,
                                                                                    self.MinMaxcheckBox,
                                                                                    self.SurfAreacheckBox,
                                                                                    self.ClosedVolumecheckBox,
                                                                                    self.VolbyAreacheckBox,
                                                                                    self.PorositycheckBox,
                                                                                    self.FiberDiametercheckBox,
                                                                                    self.FiberDiamSpherelineEdit,
                                                                                    self.PoreDistributioncheckBox,
                                                                                    self.PoreDistSpherelineEdit,
                                                                                    self.FiberAnglecheckBox,
                                                                                    self.FiberLengthcheckBox,
                                                                                    self.PlaneAnglecomboBox])
                                                       )
        self.SelectAllpushButton = self.findChild(QPushButton, 'SelectAllpushButton')
        self.SelectAllpushButton.clicked.connect(self.select_all_properties)
        
        self.UnselectAllpushButton = self.findChild(QPushButton, 'UnselectAllpushButton')
        self.UnselectAllpushButton.clicked.connect(self.unselect_all_properties)
        
        # Set up Run button
        self.RunpushButton = self.findChild(QPushButton, 'RunpushButton')
        self.RunpushButton.clicked.connect(self.run_voxel2stl)
        
        # Create Save Settings Button
        self.SaveSettingsButton = self.findChild(QPushButton, 'SaveSettingspushButton')
        self.SaveSettingsButton.clicked.connect(self.save_settings)

        # Create Load Settings Button
        self.LoadSettingsButton = self.findChild(QPushButton, 'LoadSettingspushButton')
        self.LoadSettingsButton.clicked.connect(self.load_settings)
        
        self.show()
        
    def open_file_dialog(self):
        options = QFileDialog.Options()
        file_paths, _ = QFileDialog.getOpenFileNames(
            self,  # Use self as parent
            "Select Files", 
            "",  
            "TIFF or DAT (*.tif *.tiff *.dat);;TIFF (*.tif *.tiff);; DAT (*.dat)", 
            options=options
        )
        
        if file_paths:
            display_text = f"Selected {len(file_paths)} file(s):\n" + "\n".join(file_paths[:3])
            if len(file_paths) > 3:
                display_text += "\n..."
            # self.label1.setText(display_text)
            print("Selected files:", file_paths)
            
            # Populate the table
            self.populate_table(file_paths)
            
    def populate_table(self, file_paths):
        current_row_count = self.tableWidget.rowCount()
        self.tableWidget.setRowCount(current_row_count + len(file_paths))
        
        script_dir = os.path.realpath(os.getcwd())
        
        for i, file in enumerate(file_paths):
            row = current_row_count + i
            
            file_path = os.path.abspath(file)  # Get absolute path
            if os.path.dirname(file_path) == script_dir:
                display_name = os.path.basename(file)  # Use only file name
            else:
                display_name = file_path  # Use full path
            # Add file name to first column
            self.tableWidget.setItem(row, 0, QTableWidgetItem(display_name))

            # Add editable text box to second column (default empty)
            self.tableWidget.setItem(row, 1, QTableWidgetItem("1.0"))

        # Resize to fit the number of files
        self.tableWidget.resizeRowsToContents()
    
    def add_corner_data(self):
        # Open file dialog to select .txt file
        file, _ = QFileDialog.getOpenFileName(self, "Open Corner Data File", "", "Text Files (*.txt)")

        if file:
            with open(file, 'r') as f:
                # Read each line, parse the numbers and add them to the table
                for line in f:
                    # Split the line into values
                    values = line.strip().split('\t')
                    if len(values) == 3:  # Ensure it has exactly 3 values
                        row_position = self.CornertableWidget.rowCount()
                        self.CornertableWidget.insertRow(row_position)
                        for col, value in enumerate(values):
                            self.CornertableWidget.setItem(row_position, col, QTableWidgetItem(value))
                            
    def add_manual_entry(self, manualText, table):
        entry = manualText.text().strip()
        if entry:
            row = table.rowCount()
            table.insertRow(row)
            if table == self.tableWidget:
                table.setItem(row, 0, QTableWidgetItem(entry))
                table.setItem(row, 1, QTableWidgetItem("1.0"))
            if table == self.CornertableWidget:
                entry = entry.replace(" ", "")
                entry = entry.split(',')
                table.setItem(row, 0, QTableWidgetItem(entry[0]))
                table.setItem(row, 1, QTableWidgetItem(entry[1]))
                table.setItem(row, 2, QTableWidgetItem(entry[2]))
            manualText.clear()
            
    def delete_selected_rows(self, table):
        selected_rows = sorted(set(index.row() for index in table.selectedIndexes()), reverse=True)

        for row in selected_rows:
            table.removeRow(row)
    
    def toggle_widgets(self, checkBox, widgets):
        """
        Dynamically enable/disable widgets based on the state of the primary checkbox.

        :param widget_names: A list of widget object names (strings) to enable/disable
        """

        # Iterate through the widget names list
        for widget in widgets:
            if widget is None:
                print(f"Error: Could not find widget with name {widget}")
                continue  # Skip to the next widget if one is not found
                
            elif widget == self.FiberDiamSpherelineEdit and checkBox.isChecked():
                widget.setEnabled(self.FiberDiametercheckBox.isChecked())
            elif widget == self.FiberDiamSpherelineEdit and not checkBox.isChecked():
                widget.setEnabled(False)
                
            elif widget == self.PoreDistSpherelineEdit and checkBox.isChecked():
                widget.setEnabled(self.PoreDistributioncheckBox.isChecked())
            elif widget == self.PoreDistSpherelineEdit and not checkBox.isChecked():
                widget.setEnabled(False)
            elif checkBox == self.LaplaciancheckBox and self.LaplaciancheckBox.isChecked():
                self.ScreenedPoissoncheckBox.setChecked(False)
                widget.setEnabled(checkBox.isChecked())
            elif checkBox == self.ScreenedPoissoncheckBox and self.ScreenedPoissoncheckBox.isChecked():
                self.LaplaciancheckBox.setChecked(False)
                widget.setEnabled(checkBox.isChecked())
            elif widget == self.PlaneAnglecomboBox and checkBox.isChecked():
                widget.setEnabled(self.FiberAnglecheckBox.isChecked())
            else:
                # Enable or disable the widget based on the checkbox state
                widget.setEnabled(checkBox.isChecked())
    
    def select_all_properties(self):
        """Select all property checkboxes."""
        self.MinMaxcheckBox.setChecked(True)
        self.SurfAreacheckBox.setChecked(True)
        self.ClosedVolumecheckBox.setChecked(True)
        self.VolbyAreacheckBox.setChecked(True)
        self.PorositycheckBox.setChecked(True)
        self.FiberDiametercheckBox.setChecked(True)
        self.PoreDistributioncheckBox.setChecked(True)
        self.FiberAnglecheckBox.setChecked(True)
        self.FiberLengthcheckBox.setChecked(True)
    
    def unselect_all_properties(self):
        """Unselect all property checkboxes."""
        self.MinMaxcheckBox.setChecked(False)
        self.SurfAreacheckBox.setChecked(False)
        self.ClosedVolumecheckBox.setChecked(False)
        self.VolbyAreacheckBox.setChecked(False)
        self.PorositycheckBox.setChecked(False)
        self.FiberDiametercheckBox.setChecked(False)
        self.PoreDistributioncheckBox.setChecked(False)
        self.FiberAnglecheckBox.setChecked(False)
        self.FiberLengthcheckBox.setChecked(False)
    
    def save_settings(self):
        options = QFileDialog.Options()
        file_path, _ = QFileDialog.getSaveFileName(self, "Save Settings", "", "JSON Files (*.json);;All Files (*)", options=options)
        
        if file_path:
            settings = {
                'fileNameTable': self.get_table_data(self.tableWidget),
                'cornerTable': self.get_table_data(self.CornertableWidget),
                'TiffSavePath': self.TiffSavePathtextEdit.text(),
                'VoxelSavePath': self.VoxelSavePathtextEdit.text(),
                'StlSavePath': self.StlSavePathtextEdit.text(),
                'PropertySavePath': self.PropertySavePathtextEdit.text(),
                'PropertySaveFlags': {
                    'MinMax': self.MinMaxcheckBox.isChecked(),
                    'SurfArea': self.SurfAreacheckBox.isChecked(),
                    'ClosedVolume': self.ClosedVolumecheckBox.isChecked(),
                    'VolbyArea': self.VolbyAreacheckBox.isChecked(),
                    'Porosity': self.PorositycheckBox.isChecked(),
                    'FiberDiameter': self.FiberDiametercheckBox.isChecked(),
                    'FiberDiamSphere': self.FiberDiamSpherelineEdit.text(),
                    'PoreDistribution': self.PoreDistributioncheckBox.isChecked(),
                    'PoreDistriDiamSphere': self.PoreDistSpherelineEdit.text(),
                    'FiberLength': self.FiberLengthcheckBox.isChecked(),
                    'FiberAngle': self.FiberAnglecheckBox.isChecked(),
                    'FiberAnglePlane': self.PlaneAnglecomboBox.currentText(),
                },
                
                'Laplacian': self.LaplaciancheckBox.isChecked(),
                'LaplacianIter': self.LaplacianItertextEdit.text(),
                'ScreenedPoisson': self.ScreenedPoissoncheckBox.isChecked(), 
                'ScreenedPoissonIter': self.ScreenedPoissonItertextEdit.text(),
                'RemoveIslands': self.RemoveIslandscheckBox.isChecked(),
                'VoxelLength': self.VolumnLengthlineEdit.text(),
                'VolumeLength': self.VolumnNumberlineEdit.text(),
                'VolumeLengthCorner': self.VolumnLengthCornerlineEdit.text(),
                'TiffSave': self.TiffSavecheckBox.isChecked(),
                'VoxelSave': self.VoxelSavePathcheckBox.isChecked(),
                'StlSave': self.StlSavePathcheckBox.isChecked(),
                'PropertySave': self.PropertySavecheckBox.isChecked(),
                
            }

            with open(file_path, 'w') as f:
                json.dump(settings, f, indent=4)

    def get_table_data(self, table):
        data = []
        for row in range(table.rowCount()):
            row_data = []
            for col in range(table.columnCount()):
                item = table.item(row, col)
                row_data.append(item.text() if item else "")
            data.append(row_data)
        return data
    
    def load_settings(self):
        options = QFileDialog.Options()
        file_path, _ = QFileDialog.getOpenFileName(self, "Load Settings", "", "JSON Files (*.json);;All Files (*)", options=options)
        
        if file_path:
            with open(file_path, 'r') as f:
                settings = json.load(f)

            self.load_table_data(self.tableWidget, settings.get('fileNameTable', []))
            self.load_table_data(self.CornertableWidget, settings.get('cornerTable', []))

            self.TiffSavePathtextEdit.setText(settings.get('TiffSavePath', ''))
            self.VoxelSavePathtextEdit.setText(settings.get('VoxelSavePath', ''))
            self.StlSavePathtextEdit.setText(settings.get('StlSavePath', ''))
            self.PropertySavePathtextEdit.setText(settings.get('PropertySavePath', ''))

            self.set_checkbox_state(self.MinMaxcheckBox, settings['PropertySaveFlags'].get('MinMax', False))
            self.set_checkbox_state(self.SurfAreacheckBox, settings['PropertySaveFlags'].get('SurfArea', False))
            self.set_checkbox_state(self.ClosedVolumecheckBox, settings['PropertySaveFlags'].get('ClosedVolume', False))
            self.set_checkbox_state(self.VolbyAreacheckBox, settings['PropertySaveFlags'].get('VolbyArea', False))
            self.set_checkbox_state(self.PorositycheckBox, settings['PropertySaveFlags'].get('Porosity', False))
            self.set_checkbox_state(self.FiberDiametercheckBox, settings['PropertySaveFlags'].get('FiberDiameter', False))
            self.FiberDiamSpherelineEdit.setText(settings['PropertySaveFlags'].get('FiberDiamSphere', ''))
            self.set_checkbox_state(self.PoreDistributioncheckBox, settings['PropertySaveFlags'].get('PoreDistribution', False))
            self.PoreDistSpherelineEdit.setText(settings['PropertySaveFlags'].get('PoreDistriDiamSphere', ''))
            self.set_checkbox_state(self.FiberLengthcheckBox, settings['PropertySaveFlags'].get('FiberLength', False))
            self.set_checkbox_state(self.FiberAnglecheckBox, settings['PropertySaveFlags'].get('FiberAngle', False))
            self.PlaneAnglecomboBox.setCurrentText(settings['PropertySaveFlags'].get('FiberAnglePlane', ''))

            self.set_checkbox_state(self.LaplaciancheckBox, settings.get('Laplacian', False))
            self.LaplacianItertextEdit.setText(settings.get('LaplacianIter', ''))
            self.set_checkbox_state(self.ScreenedPoissoncheckBox, settings.get('ScreenedPoisson', False))
            self.ScreenedPoissonItertextEdit.setText(settings.get('ScreenedPoissonIter', ''))
            self.set_checkbox_state(self.RemoveIslandscheckBox, settings.get('RemoveIslands', False))
            self.VolumnLengthlineEdit.setText(settings.get('VoxelLength', ''))
            self.VolumnNumberlineEdit.setText(settings.get('VolumeLength', ''))
            self.VolumnLengthCornerlineEdit.setText(settings.get('VolumeLengthCorner', ''))
            self.set_checkbox_state(self.TiffSavecheckBox, settings.get('TiffSave', False))
            self.set_checkbox_state(self.VoxelSavePathcheckBox, settings.get('VoxelSave', False))
            self.set_checkbox_state(self.StlSavePathcheckBox, settings.get('StlSave', False))
            self.set_checkbox_state(self.PropertySavecheckBox, settings.get('PropertySave', False))

    def load_table_data(self, table, data):
        # Clear the existing data in the table
        table.setRowCount(0)
        
        for row_data in data:
            row_position = table.rowCount()
            table.insertRow(row_position)
            for col, value in enumerate(row_data):
                table.setItem(row_position, col, QTableWidgetItem(value))
        
        # Resize to fit the number of files
        self.tableWidget.resizeRowsToContents()

    def set_checkbox_state(self, checkbox, state):
        checkbox.setChecked(state)
    
    def run_voxel2stl(self):
        # Check if there is at least one file with voxel size in the table
        if self.tableWidget.rowCount() == 0:
            self.show_error_message("Error", "Please add at least one file with its voxel size.")
            return
        
        # Check if either TIFF, STL, or Properties save options are selected
        tiffSelected = self.TiffSavecheckBox.isChecked()
        voxelSelected = self.VoxelSavePathcheckBox.isChecked()
        stlSelected = self.StlSavePathcheckBox.isChecked()
        propertiesSelected = self.PropertySavecheckBox.isChecked()
    
        if not (tiffSelected or voxelSelected or stlSelected or propertiesSelected):
            self.show_error_message("Error", "Please select at least one of the save options (TIFF, Voxel, STL, or Properties).")
            return
        
        # Surface Settings
        surfaceSettings = {
            "laplacianFlag": self.LaplaciancheckBox.isChecked(),
            "laplacian_iter": int(self.LaplacianItertextEdit.text()) if self.LaplaciancheckBox.isChecked() else None,
            "ScreenedPoissonFlag": self.ScreenedPoissoncheckBox.isChecked(),
            "ScreenedPoisson_iter": int(self.ScreenedPoissonItertextEdit.text()) if self.ScreenedPoissoncheckBox.isChecked() else None,
            "RemoveIslandsFlag": self.RemoveIslandscheckBox.isChecked()
            }
        
        print(surfaceSettings)
        
        active_index = self.tabWidget.currentIndex()
        # Map index to cropping flag
        cropping_flags = ["Regular", "Corners"]  # Adjust names as needed
        croppingFlag = cropping_flags[active_index] if active_index < len(cropping_flags) else None
        
        print(croppingFlag)
        
        # Extract file names and voxel sizes from table
        filenames = []
        filevoxels = []
        # Check that all files exist and voxel sizes are valid
        for row in range(self.tableWidget.rowCount()):
            file_item = self.tableWidget.item(row, 0)
            voxel_item = self.tableWidget.item(row, 1)
    
            if file_item is None or voxel_item is None:
                self.show_error_message("Error", f"Row {row+1}: Missing file name or voxel size.")
                return
    
            file_path = file_item.text().strip()
            voxel_size = voxel_item.text().strip()
    
            # Check if file exists
            if not os.path.exists(file_path):
                self.show_error_message("Error", f"File not found: {file_path}")
                return
    
            # Check if voxel size is a valid number
            try:
                voxel_size = float(voxel_size)
                if voxel_size == 0:
                    raise ValueError
            except ValueError:
                self.show_error_message("Error", f"Row {row+1}: Invalid voxel size. Please enter a number greater than 0.")
                return
    
            filenames.append(file_path)
            filevoxels.append(voxel_size)
            
        # Extract values from the CornertableWidget
        cornersMTX = []
        
        # Check that all rows are valid (integers >= 0)
        for row in range(self.CornertableWidget.rowCount()):
            # Get values from each column in the row
            corner_item_x = self.CornertableWidget.item(row, 0)  # Assuming first column is x values
            corner_item_y = self.CornertableWidget.item(row, 1)  # Assuming second column is y values
            corner_item_z = self.CornertableWidget.item(row, 2)  # Assuming third column is z values
        
            if corner_item_x is None or corner_item_y is None or corner_item_z is None:
                self.show_error_message("Error", f"Row {row+1}: Missing corner values.")
                return
        
            # Extract corner values
            try:
                corner_x = int(corner_item_x.text().strip())  # Convert to integer
                corner_y = int(corner_item_y.text().strip())  # Convert to integer
                corner_z = int(corner_item_z.text().strip())  # Convert to integer
        
                # Check if values are greater than or equal to 0
                if corner_x < 0 or corner_y < 0 or corner_z < 0:
                    raise ValueError  # Raise error if any value is less than 0
            except ValueError:
                self.show_error_message("Error", f"Row {row+1}: Invalid corner values. Please enter integers greater than or equal to 0.")
                return
        
            # Add valid entries to the list
            cornersMTX.append((corner_x, corner_y, corner_z))
            
        # Check if Fiber Diameter Sphere is required but missing
        fiber_diam_sphere = None
        if self.FiberDiametercheckBox.isChecked():
            fiber_diam_sphere_text = self.FiberDiamSpherelineEdit.text().strip()
            if not fiber_diam_sphere_text:
                self.show_error_message("Error", "Fiber Diameter Sphere value is required when 'Fiber Diameter' is selected.")
                return
            try:
                fiber_diam_sphere = float(fiber_diam_sphere_text)
            except ValueError:
                self.show_error_message("Error", "Invalid Fiber Diameter Sphere value. Please enter a valid number.")
                return
    
        # Check if Pore Distribution Sphere is required but missing
        pore_dist_sphere = None
        if self.PoreDistributioncheckBox.isChecked():
            pore_dist_sphere_text = self.PoreDistSpherelineEdit.text().strip()
            if not pore_dist_sphere_text:
                self.show_error_message("Error", "Pore Distribution Sphere value is required when 'Pore Distribution' is selected.")
                return
            try:
                pore_dist_sphere = float(pore_dist_sphere_text)
            except ValueError:
                self.show_error_message("Error", "Invalid Pore Distribution Sphere value. Please enter a valid number.")
                return
            
        # Saving Flags
        savingOptions = {
            "tiff_save": self.TiffSavecheckBox.isChecked(),
            "tiff_path": self.TiffSavePathtextEdit.text() if self.TiffSavecheckBox.isChecked() else None,
            "voxel_save": self.VoxelSavePathcheckBox.isChecked(),
            "voxel_path": self.VoxelSavePathtextEdit.text() if self.VoxelSavePathcheckBox.isChecked() else None,
            "stl_save": self.StlSavePathcheckBox.isChecked(),
            "stl_path": self.StlSavePathtextEdit.text() if self.StlSavePathcheckBox.isChecked() else None,
            "property_save": self.PropertySavecheckBox.isChecked(),
            "property_path": self.PropertySavePathtextEdit.text() if self.PropertySavecheckBox.isChecked() else None,
            "property_options": {
                "min_max": self.MinMaxcheckBox.isChecked(),
                "surf_area": self.SurfAreacheckBox.isChecked(),
                "closed_volume": self.ClosedVolumecheckBox.isChecked(),
                "vol_by_area": self.VolbyAreacheckBox.isChecked(),
                "porosity": self.PorositycheckBox.isChecked(),
                "fiber_diameter": self.FiberDiametercheckBox.isChecked(),
                "fiber_diam_sphere": int(self.FiberDiamSpherelineEdit.text()) if self.FiberDiametercheckBox.isChecked() else None,
                "pore_distribution": self.PoreDistributioncheckBox.isChecked(),
                "pore_dist_sphere": int(self.PoreDistSpherelineEdit.text()) if self.PoreDistributioncheckBox.isChecked() else None,
                "FiberAngle": self.FiberAnglecheckBox.isChecked(),
                "FiberAnglePlane": self.PlaneAnglecomboBox.currentText(),
                "FiberLength": self.FiberLengthcheckBox.isChecked(),
            }
        }
        
        print(savingOptions)
        
        if croppingFlag == 'Regular':
            # Check if volume length and number of volumes are filled
            volumeLength = self.VolumnLengthlineEdit.text().strip()
            numVolumes = self.VolumnNumberlineEdit.text().strip()
            
            if not volumeLength or not numVolumes:
                self.show_error_message("Error", "Please enter both the volume length and the number of volumes.")
                return
            
            volumeLength = int(self.VolumnLengthlineEdit.text())
            numVolumes = int(self.VolumnNumberlineEdit.text())
            cropSettings = filenames, filevoxels, numVolumes, volumeLength
            print(cropSettings)
        elif croppingFlag == 'Corners':
            volumeLength = self.VolumnLengthCornerlineEdit.text().strip()
            
            if not volumeLength:
                self.show_error_message("Error", "Please enter the volume length.")
                return
            volumeLength = int(self.VolumnLengthCornerlineEdit.text())
            
            cropSettings = filenames, filevoxels, cornersMTX, volumeLength
            print(cropSettings)
        # Close the UI window
        self.close()
        
        voxel2stl(croppingFlag, cropSettings, surfaceSettings, savingOptions)
        
        
    def show_error_message(self, title, message):
        """Displays an error message box."""
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Critical)
        msg.setText(message)
        msg.setWindowTitle(title)
        msg.exec_()

def window():
    app = QApplication(sys.argv)
    app.setAttribute(Qt.AA_EnableHighDpiScaling) # Enable High DPI Scaling 
    app.setAttribute(Qt.AA_UseHighDpiPixmaps)
    app.setStyle("Fusion")
    ui = UI()
    ui.show()
    sys.exit(app.exec_())

def voxel2stl(croppingFlag, cropSettings, surfaceSettings, savingOptions):
    
    if croppingFlag == 'Regular':
        filenames, filevoxels, numVolumes, volumeLength = cropSettings
    
    elif croppingFlag == 'Corners':
        filenames, filevoxels, cornersMTX, volumeLength = cropSettings
        
    
    # matrix to store Volumes data 
    sim_mtx = [] #
    if croppingFlag == 'Regular':
        if volumeLength != 0 and numVolumes != 0:
            tempMTX= np.zeros(len(filenames),dtype= 'int')
            for temp in range(numVolumes):
                tempName = random.choice(filenames)
                tempNameIndex = filenames.index(tempName)
                tempMTX[tempNameIndex] += 1
     
    temp_number = 0
    for surf in filenames:
        tempNameIndex = filenames.index(surf)
        
        # Load data
        image_volume = loadData(surf)
                
        # max voxel length in x, y, and z
        voxelsLegth = (image_volume.shape[0],image_volume.shape[1],image_volume.shape[2])
        
        if croppingFlag == 'Regular':
            if volumeLength == 0: # create stl from all the volume
                corner = np.zeros(3, dtype='int')
                fullvolume = 'Full'
                getstl(surf, filevoxels[tempNameIndex], temp_number,fullvolume, corner, surfaceSettings, savingOptions)
                temp_number += 1
            
            elif numVolumes == 0:
                # Number of volumes in each direction
                dimX = int(voxelsLegth[0]*filevoxels[tempNameIndex]/volumeLength)
                dimY = int(voxelsLegth[0]*filevoxels[tempNameIndex]/volumeLength)
                dimZ = int(voxelsLegth[0]*filevoxels[tempNameIndex]/volumeLength)
                
                totalvolumes = dimX*dimY*dimZ
                # if totalvolumes > 10:
                #     print('Do this in parallel, %i volumes'%(totalvolumes))
                #     return
                xCorners = [i*int(volumeLength/filevoxels[tempNameIndex]) for i in range(dimX)]
                yCorners = [i*int(volumeLength/filevoxels[tempNameIndex]) for i in range(dimY)]
                zCorners = [i*int(volumeLength/filevoxels[tempNameIndex]) for i in range(dimZ)]
                corners = list(itertools.product(xCorners,yCorners,zCorners))
                for corner in corners:
                    getstl(surf, filevoxels[tempNameIndex], temp_number,volumeLength, corner, surfaceSettings, savingOptions)
                    temp_number += 1
                    
            else:
                for times in range(tempMTX[tempNameIndex]):
                    
                    print('corner',times,'of',surf)
                    if numVolumes != 0:
                         
                        # name of iteration volume
                        # tempName = filenames[:-4]+'_V%i'%(temp)
                        
                        corner = np.zeros(3, dtype='int')
                        # get random temp corner
                        corner[0] = random.randint(0,int(voxelsLegth[0]-volumeLength)) 
                        corner[1] = random.randint(0,int(voxelsLegth[1]-volumeLength))
                        corner[2] = random.randint(0,int(voxelsLegth[2]-volumeLength))
                        # center crop
                        # corner[0] = (voxelsLegth[0]-volumeLength)/2 #random.randint(0,voxelsLegth[0]-volumeLength) 
                        # corner[1] = (voxelsLegth[1]-volumeLength)/2 #random.randint(0,voxelsLegth[1]-volumeLength)
                        # corner[2] = (voxelsLegth[2]-volumeLength)/2 #random.randint(0,voxelsLegth[2]-volumeLength)

                        
                        getstl(surf, filevoxels[tempNameIndex], temp_number,volumeLength, corner, surfaceSettings, savingOptions)
                        temp_number += 1

        elif croppingFlag == 'Corners':
            for corner in cornersMTX:
                getstl(surf, filevoxels[tempNameIndex], temp_number,volumeLength, corner, surfaceSettings, savingOptions)
                temp_number += 1

def loadData(surf):
    if surf.endswith('.tif'):
        # Load the TIFF file
        image_volume = imageio.volread(surf)
    
    elif surf.endswith('.txt') or surf.endswith('.dat'):
        tempdata = np.loadtxt(surf, skiprows=2)
        xmax = int(max(tempdata[:, 0]))
        ymax = int(max(tempdata[:, 1]))
        zmax = int(max(tempdata[:, 2]))
        image_volume = np.zeros((xmax, ymax, zmax), dtype='int')
        for val in tempdata:
            image_volume[int(val[0]) - 1, int(val[1]) - 1, int(val[2]) - 1] = int(val[3])
            
    return image_volume

def getstl(surfacename, tifvoxelsize, temp_number,volumeLength, corner, surfaceSettings, savingOptions): 
    
    # Create image_volume
    image_volume = loadData(surfacename)

    # Surface file name
    tempName = surfacename[:-4]+'_V%i_%i-%i-%i-%s'%(temp_number,corner[0],corner[1],corner[2],volumeLength)
    
    if volumeLength != 'Full':
        # adjust nummber volumelength 
        volumeLength = int(volumeLength/tifvoxelsize)
        
        # Crop the volume of interest
        temp_volume = image_volume[corner[0]:corner[0]+volumeLength,corner[1]:corner[1]+volumeLength,corner[2]:corner[2]+volumeLength]
        
    else: # Create stl from full tif
        temp_volume = image_volume
    
    if np.sum(temp_volume) == 0:
        print('Empty Volume, there is no material!')
        return 'Empty'
    # Make a binary MTX
    temp_volume = temp_volume/ np.max(temp_volume)
    
    # Creat padding around volume 
    binary_volume = createPadding(temp_volume)
    
    # Remove Ilands
    if savingOptions['voxel_save']:
        if savingOptions['voxel_path'] != '':
            if not os.path.exists(savingOptions['voxel_path']):
                Path(savingOptions['voxel_path']).mkdir(parents=True, exist_ok=True) 
            writeChenFormat(os.path.join(savingOptions['voxel_path'],os.path.basename(tempName))+'.dat',binary_volume,tifvoxelsize)
        else:
            writeChenFormat(os.path.basename(tempName)+'.dat',binary_volume,tifvoxelsize)
        
    # Get vertices and faces 
    vertices, faces = getMesh(binary_volume,volumeLength,tifvoxelsize)
    
    # Perform smoothing 
    tempName, vertices, faces = stlSmoothing(tempName, vertices, faces, surfaceSettings)   
    
    if savingOptions['property_save']:
        computeProperties(os.path.basename(tempName)+'.stl', vertices,faces,temp_volume,tifvoxelsize,savingOptions)
        
    if savingOptions['stl_save']:
        trimesh_mesh = loadMeshTrimesh(vertices,faces)
        if savingOptions['stl_path'] != '':
            if not os.path.exists(savingOptions['stl_path']):
                Path(savingOptions['stl_path']).mkdir(parents=True, exist_ok=True)
            # Load mesh from vertices and faces
            trimesh_mesh.export(os.path.join(savingOptions['stl_path'],os.path.basename(tempName)+'.stl') , file_type="stl_ascii")
        else:
            trimesh_mesh.export(os.path.basename(tempName)+'.stl', file_type="stl_ascii")
            
    if savingOptions['tiff_save']:
        if savingOptions['tiff_path'] != '':
            if not os.path.exists(savingOptions['tiff_path']):
                Path(savingOptions['tiff_path']).mkdir(parents=True, exist_ok=True)
            # Save the volume as a 3D TIFF file (uncomment to double check stl)[:-4]
            tiff.imwrite(os.path.join(savingOptions['tiff_path'],os.path.basename(tempName)+'.tif'), binary_volume[1:-1,1:-1,1:-1].astype(np.uint16),imagej=True)
        else:
            # Save the volume as a 3D TIFF file (uncomment to double check stl)[:-4]
            tiff.imwrite(os.path.basename(tempName)+'.tif', binary_volume[1:-1,1:-1,1:-1].astype(np.uint16),imagej=True)
    

def createPadding(image_volume):
    # Set the desired padding size (in pixels) for each dimension
    padding_size = 1  # Adjust this value based on your needs
    
    # Create a padded volume with the same data type as the original image
    padded_volume = np.zeros(
        (image_volume.shape[0] + 2 * padding_size,
         image_volume.shape[1] + 2 * padding_size,
         image_volume.shape[2] + 2 * padding_size),
        dtype=image_volume.dtype,
    )
    
    # Calculate padding ranges for each dimension
    x_range = slice(padding_size, padding_size + image_volume.shape[0])
    y_range = slice(padding_size, padding_size + image_volume.shape[1])
    z_range = slice(padding_size, padding_size + image_volume.shape[2])
    
    # Copy the original image into the center of the padded volume
    padded_volume[x_range, y_range, z_range] = image_volume
    
    
    #Load padded volume
    binary_volume = np.squeeze(np.array(padded_volume))
    
    return binary_volume

def writeChenFormat(tempName,binary_volume,tifvoxelsize):
    file1 = open(tempName,'w')
    #chen files
    x_i,y_j,z_k = np.shape(binary_volume)
    file1.write(str(x_i-1)+' '+str(y_j-1)+' '+str(z_k-1)+' '+str(tifvoxelsize*10**-6)+'\n')
    file1.write("i j k voxel")
    count = 1
    for i in range(x_i):
        for j in range(y_j):
            for k in range(z_k):
                if binary_volume[i, j, k] == 1:
                   value = int(binary_volume[i, j, k])
                   file1.write(f"\n{i} {j} {k} {value}")
                   count = count + 1
                   # print(f"Point ({i}, {j}, {k}) has a value of 1")
                # else:
                    # print(f"Point ({i}, {j}, {k}) does not have a value of 1")#print(f"Point ({i}, {j}, {k}): {temp_volume[i, j, k]}")
    file1.close()

def getMesh(binary_volume,length,voxel_size):
    
    # Create a mesh using the marching cubes algorithm
    vertices, faces, _, _ = measure.marching_cubes(binary_volume)  ##add the parallel marching cubes here
    
    # Swap x and z to make it match the tif
    # Indices of the columns you want to swap
    column_index1 = 0  # Replace with the index of the first column
    column_index2 = 2  # Replace with the index of the second column
    
    # Swap the columns using array indexing
    vertices[:, [column_index1, column_index2]] = vertices[:, [column_index2, column_index1]]
 
    # Convert vertices to physical coordinates using voxel size
    vertices = vertices * voxel_size - voxel_size
    
    return vertices, faces

def stlSmoothing(FileName, vertices, faces, surfaceSettings ):
    
    # basestl = FileName+"no-smoothing.stl"
    # print('Start saving',basestl)
    # trimesh_mesh.export(basestl, file_type="stl_ascii")
    # print('Finish saving',basestl)
    
    # Apply filter iteration i
    if surfaceSettings['laplacianFlag']:
        # Load mesh from vertices and faces
        trimesh_mesh = loadMeshTrimesh(vertices,faces)
        filterName = '_laplacian'+str(surfaceSettings['laplacian_iter'])
        trimesh_mesh = trimesh.smoothing.filter_laplacian(trimesh_mesh, lamb=0.5, iterations=surfaceSettings['laplacian_iter'], volume_constraint=True)
        faces = trimesh_mesh.faces
        vertices = trimesh_mesh.vertices
        
    elif surfaceSettings['ScreenedPoissonFlag']:
        filterName = '_screened_poisson'+str(surfaceSettings['ScreenedPoisson_iter'])
        # Load mesh 
        ms = loadMeshPymeshlab(vertices,faces)
        ms.apply_filter('generate_surface_reconstruction_screened_poisson', depth=surfaceSettings['ScreenedPoisson_iter'], preclean=True)
        mesh = ms.current_mesh()
        vertices = mesh.vertex_matrix()
        faces = mesh.face_matrix() 
    else:
        filterName = ''
    
    if surfaceSettings['RemoveIslandsFlag']: 
        ms = remove_floating_islands_Stl(vertices,faces)
        removeIsland = '_NI'
        mesh = ms.current_mesh()
        vertices = mesh.vertex_matrix()
        faces = mesh.face_matrix()
    else:
        removeIsland = ''
        
    FileName = FileName+filterName+removeIsland
    
    return FileName, vertices, faces

def loadMeshTrimesh(vertices,faces):
    return trimesh.Trimesh(vertices=vertices, faces=faces)

def loadMeshPymeshlab(vertices,faces):
    import pymeshlab as ml
    # Create meshLab mesh from vertices and faces
    meshTarget = ml.Mesh(vertices,faces)
    
    # Create a MeshSet object
    ms = ml.MeshSet(verbose=True)
    
    ms.add_mesh(meshTarget)
    
    return ms

def remove_floating_islands_Stl(vertices,faces):

    # Load the mesh
    ms = loadMeshPymeshlab(vertices,faces)

    # Compute connected components and select small components for deletion
    ms.apply_filter('compute_selection_by_small_disconnected_components_per_face',nbfaceratio=1)

    # Delete the selected small components
    ms.apply_filter('meshing_remove_selected_vertices_and_faces')

    return ms

def computeProperties(stlName, vertices, faces, temp_volume, tifvoxelsize, savingOptions):
    propertyList = [stlName]
    propertyNames = ['StlName']  # To store the names of selected properties

    if savingOptions['property_options']['min_max']:
        min_extents = np.min(vertices, axis=0)
        max_extents = np.max(vertices, axis=0)
        propertyList.extend([min_extents, max_extents])
        propertyNames.extend(["MinExtentsX", "MinExtentsY", "MinExtentsZ",
                              "MaxExtentsX", "MaxExtentsY", "MaxExtentsZ"])

    if savingOptions['property_options']['surf_area'] or savingOptions['property_options']['closed_volume'] or savingOptions['property_options']['porosity'] or savingOptions['property_options']['vol_by_area']:
        trimesh_mesh = loadMeshTrimesh(vertices, faces)
        mesh_volume = trimesh_mesh.volume
        mesh_surface_area = trimesh_mesh.area
        
    if savingOptions['property_options']['surf_area']:
        propertyList.append(mesh_surface_area)
        propertyNames.append("SurfaceArea")

    if savingOptions['property_options']['closed_volume']:
        propertyList.append(mesh_volume)
        propertyNames.append("ClosedVolume")

    if savingOptions['property_options']['vol_by_area']:
        lengthbyarea = mesh_volume / mesh_surface_area
        propertyList.append(lengthbyarea)
        propertyNames.append("Volume/SurfaceArea")

    if savingOptions['property_options']['porosity']:
        fulltempVolume = temp_volume.shape[0] * temp_volume.shape[1] * temp_volume.shape[2] * tifvoxelsize**3
        porosity = 1 - (mesh_volume / fulltempVolume)
        propertyList.append(porosity)
        propertyNames.append("Porosity")

    if savingOptions['property_options']['fiber_diameter']:
        meanDiameter, stdDiameter = getDiamter(temp_volume, tifvoxelsize,savingOptions['property_options']['fiber_diam_sphere'])
        propertyList.append(meanDiameter)
        propertyList.append(stdDiameter)
        propertyNames.extend(["fiber_diameter_Mean", "fiber_diameter_Std"])

    if savingOptions['property_options']['pore_distribution']:
        pore_diameter = getPoreDistribution(temp_volume, tifvoxelsize)
        propertyList.append(pore_diameter)
        propertyNames.append("poredistribution")
    
    
    if savingOptions['property_options']['FiberAngle'] or savingOptions['property_options']['FiberLength']:
        azimuthMean, elevationMean, lengthMean, azimuthSTD, elevationSTD,lengthSTD  = analyseCenterLine(temp_volume,tifvoxelsize,savingOptions['property_options']['FiberAnglePlane'])
        if savingOptions['property_options']['FiberAngle']:
            propertyList.append(azimuthMean)
            propertyNames.append("MeanAzimuthAngle")
            propertyList.append(azimuthSTD)
            propertyNames.append("StDAzimuthAngle")
            propertyList.append(elevationMean)
            propertyNames.append("MeanElevationAngle")
            propertyList.append(elevationSTD)
            propertyNames.append("StDElevationAngle")
        if savingOptions['property_options']['FiberLength']:
            propertyList.append(lengthMean)
            propertyNames.append("MeanLength")
            propertyList.append(lengthSTD)
            propertyNames.append("StDLength")
        
    writeProperties(savingOptions, propertyNames, propertyList)

def getDiamter(image_volume,tifvoxelsize,sphereSize):
    # Distance transform
    distance_transform = distance_transform_edt(image_volume)
    
    # Detect local maxima
    local_maxima_coords = peak_local_max(distance_transform, min_distance=int(sphereSize/2), labels=image_volume.astype(int))
    
    # Measure diameters
    fiber_diameters = []
    
    for max_coords in local_maxima_coords:
        distances = distance_transform[tuple(max_coords)]
        fiber_diameters.append(2 * np.max(distances))
    
    # Scale given voxel size
    fiber_diameters = np.multiply(fiber_diameters,tifvoxelsize)-tifvoxelsize/2
    
    meanDiameter = np.mean(fiber_diameters)
    stdDiameter = np.std(fiber_diameters)
    
    return meanDiameter, stdDiameter

def analyseCenterLine(image,tifvoxelsize,plane='XY'):
    
    # Preprocess the image
    # Apply Gaussian filter with sigma=2
    image_smoothed = filters.gaussian(image, sigma=1)
    
    # Convert to binary: 1 for values greater than the threshold, 0 otherwise
    image_smoothed = (image_smoothed >= np.max(image_smoothed) * 0.5).astype(np.uint8)
    
    # Skeletonize the image
    skeleton = morphology.skeletonize(image_smoothed)
    
    # tiff.imwrite(fileName[:-4]+'_skeleton.tif', skeleton.astype(np.uint16),imagej=True)
    
    # Extract centerline coordinates
    coords = np.column_stack(np.where(skeleton > 0))  # Get (Z, Y, X) coordinates
    
    # Build graph from skeleton pixels
    G = nx.Graph()
    for z, y, x in coords:
        G.add_node((z, y, x))
    
    # Define 26-connectivity neighbors
    neighbors_26 = [(dz, dy, dx) for dz in [-1, 0, 1] 
                                    for dy in [-1, 0, 1] 
                                    for dx in [-1, 0, 1] if not (dz == dy == dx == 0)]
    
    # Set a **distance threshold** to avoid unwanted shortcuts
    max_distance = np.sqrt(3)  # Maximum Euclidean distance for direct neighbors
    
    
    # Connect neighboring pixels while **pruning bad connections**
    for z, y, x in coords:
        for dz, dy, dx in neighbors_26:
            neighbor = (z+dz, y+dy, x+dx)
            if neighbor in G:
                # Compute Euclidean distance
                distance = np.linalg.norm(np.array([z, y, x]) - np.array(neighbor))
                if distance <= max_distance:
                    G.add_edge((z, y, x), neighbor, weight=distance)
    
    # Compute the **Minimal Spanning Tree (MST)** to remove unwanted edges
    MST = nx.minimum_spanning_tree(G)
    
    # Identify true branch points (nodes with degree > 2)
    branch_points = [node for node in MST.nodes() if MST.degree(node) > 2]
    
    # Split centerlines at detected branch points
    split_centerlines, graph_centerlines = split_and_order_centerlines(MST, branch_points)
    
    # Number of centerlines before and after split
    num_centerlines = len(list(nx.connected_components(MST)))
    num_split_centerlines = len(split_centerlines)
    
    
    # labeled_image = assign_voxels_to_centerlines_with_kdtree(image, split_centerlines)
    
    # tiff.imwrite(fileName[:-4]+'test.tif', labeled_image.astype(np.uint16),imagej=True)
    
    # plot_centerlines_and_voxels(image, split_centerlines, labeled_image)
    
    # Compute angles
    centerline_properties = calculate_centerline_properties(split_centerlines,tifvoxelsize,plane=plane)
    
    azimuthMean,elevationMean,lengthMean = np.mean(centerline_properties,axis=0)
    azimuthSTD, elevationSTD,lengthSTD = np.std(centerline_properties, axis=0, ddof=0)
    
    return azimuthMean,elevationMean,lengthMean, azimuthSTD, elevationSTD,lengthSTD 

# Function to split centerlines at branch points
def split_and_order_centerlines(graph, branch_nodes, steps=4):
    """
    Splits the graph's centerlines at branch points with improved handling of intersections.
    Instead of removing the branch node itself, it looks at the connected branches and removes
    (shifts) the voxel from the branch with the most deviated direction.
    
    Parameters:
        graph (networkx.Graph): The input graph representing the skeleton.
        branch_nodes (list): List of nodes where branches occur.
        steps (int): How many voxels along the branch to consider for adjustment (default=1).
        
    Returns:
        tuple: (split_centerlines, modified_graph)
            - split_centerlines: a list of ordered centerline node lists.
            - modified_graph: the graph after branch adjustment.
    """
    # Work on a copy so that the original graph is not modified
    G = graph.copy()
    
    # For each branch node, adjust the intersection by removing the first voxel
    # along the branch that deviates most from the others.
    for branch in branch_nodes:
        neighbors = list(G.neighbors(branch))
        if len(neighbors) <= 1:
            # Not really an intersection if only one neighbor.
            continue
        
        branch_vectors = {}
        # For each connected branch from the branch node, compute a unit direction vector.
        for n in neighbors:
            # If possible, follow the branch "steps" voxels ahead.
            current = n
            prev = branch
            for _ in range(steps - 1):
                # Look for a neighbor that is not the previous node.
                next_candidates = [nbr for nbr in G.neighbors(current) if nbr != prev]
                if next_candidates:
                    prev = current
                    current = next_candidates[0]
                else:
                    break
            # Compute vector from branch to the voxel 'current'
            vec = np.array(current) - np.array(branch)
            norm = np.linalg.norm(vec)
            if norm != 0:
                branch_vectors[n] = vec / norm
        
        if len(branch_vectors) < 2:
            # Not enough branches to compare
            continue
        
        # Compute total angular difference for each branch direction
        differences = {}
        for n1, v1 in branch_vectors.items():
            total_angle = 0
            for n2, v2 in branch_vectors.items():
                if n1 == n2:
                    continue
                # Compute angle difference using dot product
                dot = np.dot(v1, v2)
                # Clip dot to avoid numerical issues
                dot = np.clip(dot, -1, 1)
                angle = np.arccos(dot)
                total_angle += angle
            differences[n1] = total_angle
        
        # Identify the neighbor whose branch has the maximum total angular difference.
        branch_to_adjust = max(differences, key=differences.get)
        
        # Instead of removing the branch node, remove the neighbor on the branch that is most different.
        if branch_to_adjust in G:
            G.remove_node(branch_to_adjust)
    
    # After adjusting the intersections, split the modified graph into ordered centerlines.
    split_centerlines = []

    # Process each connected component separately
    for component in nx.connected_components(G):
        subgraph = G.subgraph(component)

        # Find endpoints (nodes with only 1 adjacent node)
        endpoints = [node for node in component if len(subgraph._adj[node]) == 1]

        if len(endpoints) < 2:
            # If no clear start, just keep it as is
            split_centerlines.append(list(component))
            continue

        # Start from one of the endpoints
        start = endpoints[0]
        ordered_centerline = []
        visited = set()

        # Traverse from start node in order
        node = start
        while node is not None:
            ordered_centerline.append(node)
            visited.add(node)

            # Move to next node
            next_nodes = [n for n in subgraph._adj[node] if n not in visited]
            node = next_nodes[0] if next_nodes else None  # Pick the next unvisited node

        split_centerlines.append(ordered_centerline)

    return split_centerlines, G

def calculate_centerline_properties(split_centerlines,tifvoxelsize, plane='XY'):
    """
    Calculates the average azimuth and elevation angles along with length 
    for each centerline based on ordered points. The plane parameter specifies 
    from which plane the angles are computed.

    Parameters:
        split_centerlines (list of lists): Ordered centerlines, each a list of (x, y, z) tuples.
        plane (str): The reference plane for azimuth and elevation calculation. 
                     Options: 'xy', 'xz', 'yz'.

    Returns:
        list of tuples: [(avg_azimuth, avg_elevation, length) for each centerline]
    """
    centerline_properties = []

    for centerline in split_centerlines:
        vectors = []
        length = 0.0
        
        # Compute direction vectors and segment lengths
        for i in range(len(centerline) - 1):
            p1 = np.array(centerline[i])  
            p2 = np.array(centerline[i + 1])
            vec = p2 - p1  
            vectors.append(vec)
            length += np.linalg.norm(vec)*tifvoxelsize  # Sum Euclidean distances

        if not vectors:
            # centerline_properties.append([None, None, 0.0])
            continue

        vectors = np.array(vectors)
        
        # Compute mean direction vector
        mean_vector = np.mean(vectors, axis=0)
        norm = np.linalg.norm(mean_vector)

        if norm == 0:
            # centerline_properties.append([None, None, length])
            continue

        # Compute azimuth and elevation based on selected plane
        if plane == 'XY':
            avg_azimuth = np.arctan2(mean_vector[1], mean_vector[2])  # θ (rotation in XY)
            avg_elevation = np.arcsin(mean_vector[0] / norm)  # φ (tilt in Z)
        elif plane == 'XZ':
            avg_azimuth = np.arctan2(mean_vector[0], mean_vector[2])  # θ (rotation in XZ)
            avg_elevation = np.arcsin(mean_vector[1] / norm)  # φ (tilt in Y)
        elif plane == 'YZ':
            avg_azimuth = np.arctan2(mean_vector[0], mean_vector[1])  # θ (rotation in YZ)
            avg_elevation = np.arcsin(mean_vector[2] / norm)  # φ (tilt in X)
        else:
            raise ValueError("Invalid plane option. Choose from 'xy', 'xz', or 'yz'.")

        centerline_properties.append([float(np.degrees(avg_azimuth)), float(np.degrees(avg_elevation)), float(length)])

    return np.array(centerline_properties,dtype=float)

def writeProperties(savingOptions, propertyNames, propertiesList):
    
    if savingOptions['property_path'] == '':
        savingOptions['property_path'] = 'propertyFile.txt' 
    
    
    # Check if file exists to determine if we need to create a new name
    file_exists = os.path.exists(savingOptions['property_path'])
    
    if re.search(r'_V(\d+)_', propertiesList[0]).group(1) == '0':
        if file_exists:
            # Create a new name for the file with '_copy' and increment if needed
            base_name, ext = os.path.splitext(savingOptions['property_path'])
            copy_fileName = f"{base_name}_copy{ext}"
    
            # If the file copy already exists, increment the number until a unique name is found
            counter = 1
            while os.path.exists(copy_fileName):
                copy_fileName = f"{base_name}_copy{counter}{ext}"
                counter += 1
            
            # Update fileName to the new copy file name
            savingOptions['property_path'] = copy_fileName
        
        
        # Open the new file in write mode to save the data
        with open(savingOptions['property_path'], 'w') as f:
            # Write headers
            f.write('\t'.join(propertyNames) + '\n')
            
            # Write the property values
            f.write('\t'.join(f"{float(x):.4f}" if (isinstance(x, (int, float)) or (isinstance(x, str) and x.replace('.', '', 1).replace('e-', '', 1).replace('e+', '', 1).isdigit())) and abs(float(x)) >= 1e-4  
                else f"{float(x):.4g}" if isinstance(x, (int, float)) or (isinstance(x, str) and x.replace('.', '', 1).replace('e-', '', 1).replace('e+', '', 1).isdigit())  
                else str(x) for x in propertiesList) + '\n')

    else:
        with open(savingOptions['property_path'], '+a') as f:
            # Write the property values
            f.write('\t'.join(f"{float(x):.4f}" if (isinstance(x, (int, float)) or (isinstance(x, str) and x.replace('.', '', 1).replace('e-', '', 1).replace('e+', '', 1).isdigit())) and abs(float(x)) >= 1e-4  
                else f"{float(x):.4g}" if isinstance(x, (int, float)) or (isinstance(x, str) and x.replace('.', '', 1).replace('e-', '', 1).replace('e+', '', 1).isdigit())  
                else str(x) for x in propertiesList) + '\n')

        
if __name__ == "__main__":
    window()
