# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\GuiTest.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import uic
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import ( 
    QApplication, QMainWindow, QPushButton, QLabel, QFileDialog,
    QTableWidget, QTableWidgetItem, QHeaderView,QLineEdit, QCheckBox,
    QWidget, QMessageBox, QComboBox, QSlider, QGraphicsView, QGraphicsScene,
    QVBoxLayout, QSizePolicy, QProgressBar, QDialog
 )
from PyQt5.QtGui import QDoubleValidator, QIntValidator, QRegularExpressionValidator
from PyQt5.QtCore import QRegularExpression, QThread, pyqtSignal
from PyQt5.QtGui import QImage, QPixmap
import sys
import os
from pathlib import Path
import numpy as np 
import tifffile as tiff
import json
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
import matplotlib.pyplot as plt
from matplotlib.widgets import RectangleSelector
import pyvista as pv
from pyvistaqt import BackgroundPlotter, QtInteractor
from hermes.gui_adapter import (
    GuiAdapterError,
    build_workflow_config,
    gui_settings_from_workflow_config,
)
from hermes.segmentation import segment_greyscale
from hermes.workflow import run_workflow_config

class VoxelRenderingWindow(QDialog):
    def __init__(self, voxel_data, VoxelSizeX, VoxelSizeY, VoxelSizeZ, parent=None):
        if VoxelSizeX == '':
            VoxelSizeX = 1
        else:
            VoxelSizeX = int(VoxelSizeX)
        if VoxelSizeY == '':
            VoxelSizeY = 1
        else:
            VoxelSizeY = int(VoxelSizeY)
        if VoxelSizeZ == '':
            VoxelSizeZ = 1
        else:
            VoxelSizeZ = int(VoxelSizeZ)
            
        super().__init__(parent)
        self.setWindowTitle("Voxel Rendering")
        self.resize(800, 600)

        layout = QVBoxLayout(self)
        
        # Convert voxel data to integer (0 or 1)
        voxel_data_int = voxel_data.astype(int)
        
        # Convert voxel data to PyVista format
        grid = pv.ImageData()
        grid.dimensions = np.array(voxel_data_int.shape) + 1  # PyVista requires +1
        grid.spacing = (VoxelSizeX, VoxelSizeY, VoxelSizeZ)  # Adjust voxel size if needed
        grid.cell_data["values"] = voxel_data_int.flatten(order="F")  # Flatten for PyVista
        
        # **Thresholding to remove zero-valued voxels**
        thresholded_grid = grid.threshold(0.5)  # Keeps values > 0
        
        # **Extract the outer surface** (Required for smoothing)
        surface = thresholded_grid.extract_surface()
        
        # Create a plotter using QtInteractor (to embed in PyQt5 window)
        self.plotter = QtInteractor(self)
        
        # Add the smoothed volume to the plot
        self.plotter.add_mesh(surface, show_edges=False, opacity=1.0, cmap="coolwarm")
        
        # Add axes to show X, Y, Z directions
        self.plotter.show_axes()
        
        # Remove the scalar bar
        self.plotter.remove_scalar_bar()
        
        # Layout for PyQt5 window
        layout.addWidget(self.plotter.interactor)
        self.setLayout(layout)
        
    def closeEvent(self, event):
        # Ensure that the plotter window is closed properly
        self.plotter.close()
        event.accept()
        
class SegmentationThread(QThread):
    finished = pyqtSignal(np.ndarray, str, str, float)

    def __init__(self, image_data, method, GreyScaleSelectionindex, Blocksize=51, minManual=0,maxManual=255):
        super().__init__()
        self.image_data = image_data
        self.method = method
        self.GreyScaleSelectionindex = GreyScaleSelectionindex
        self.Blocksize = Blocksize
        self.minManual = minManual
        self.maxManual = maxManual

        
    def run(self):
        try:
            block_size = self._coerce_int_input(self.Blocksize, default=51)
            min_manual = self._coerce_int_input(self.minManual, default=0)
            max_manual = self._coerce_int_input(self.maxManual, default=255)
            result = segment_greyscale(
                self.image_data,
                self.method,
                select_lighter=self.GreyScaleSelectionindex == 0,
                block_size=block_size,
                min_manual=min_manual,
                max_manual=max_manual,
            )
        except ValueError as exc:
            self.show_error_message("Invalid Segmentation Input", str(exc))
            return

        self.finished.emit(
            result.mask,
            str(result.min_threshold),
            str(result.max_threshold),
            result.porosity,
        )

    @staticmethod
    def _coerce_int_input(value, default):
        if hasattr(value, "text"):
            value = value.text()
        if value == "":
            return default
        return int(value)

    def show_error_message(self, title, message):
        """Displays an error message box."""
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Critical)
        msg.setText(message)
        msg.setWindowTitle(title)
        msg.exec_()
        
class UI(QMainWindow):
    def __init__(self):
        super(UI,self).__init__()
        
        uic.loadUi('HERMESGUI.ui',self)
        

        # Create delete button
        self.AddButton = self.findChild(QPushButton, 'AddButton')
        self.AddButton.clicked.connect(lambda: self.add_manual_entry(self.manualInput,self.tableWidget))
        
        # Set up Manual Name
        self.manualInput = self.findChild(QLineEdit, 'FileNamelineEdit')
        self.manualInput.setPlaceholderText("Enter file name manually...")
        
        # Set up find Menue
        self.FindButton = self.findChild(QPushButton, 'FindButton')
        self.FindButton.clicked.connect(self.open_file_dialog)
        
        # Set up table properties
        self.tableWidget = self.findChild(QTableWidget, 'FileNamestableWidget')
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setHorizontalHeaderLabels(["File Name", "Voxel Size"])
        self.tableWidget.setColumnWidth(0, 250)  # Adjust column width
        self.tableWidget.setColumnWidth(1, 100)
        self.tableWidget.setSelectionBehavior(QTableWidget.SelectRows)  # Select entire rows
        self.tableWidget.setSelectionMode(QTableWidget.ExtendedSelection)  # Allow selecting one row at a time
        self.tableWidget.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        
        # Create delete button
        self.DeleteButton = self.findChild(QPushButton, 'DeleteButton')
        self.DeleteButton.clicked.connect(lambda: self.delete_selected_rows(self.tableWidget))
        
        # Set a QDoubleValidator to only allow floating-point numbers
        float_validator = QDoubleValidator()
        float_validator.setRange(0, 999999, 5)
        float_validator.setNotation(QDoubleValidator.StandardNotation)  # Allows standard float notation
        
        int_validator = self.int_validator = QIntValidator(0, 99999999)
        
        # Set up Laplacian Filter
        self.LaplaciancheckBox = self.findChild(QCheckBox, 'LaplaciancheckBox')
        self.LaplacianItertextEdit = self.findChild(QLineEdit, 'LaplacianItertextEdit')
        self.LaplacianItertextEdit.setValidator(int_validator)
        
        # Initially disable the line edit if the checkbox is not checked
        self.LaplacianItertextEdit.setEnabled(self.LaplaciancheckBox.isChecked())
        
        # Connect the checkbox state change to a function
        self.LaplaciancheckBox.stateChanged.connect(lambda: self.toggle_widgets(self.LaplaciancheckBox, [self.LaplacianItertextEdit]))
        
        # Set up Laplacian Filter
        self.ScreenedPoissoncheckBox = self.findChild(QCheckBox, 'ScreenedPoissoncheckBox')
        self.ScreenedPoissonItertextEdit = self.findChild(QLineEdit, 'ScreenedPoissonItertextEdit')
        self.ScreenedPoissonItertextEdit.setValidator(int_validator)
        
        # Initially disable the line edit if the checkbox is not checked
        self.ScreenedPoissonItertextEdit.setEnabled(self.ScreenedPoissoncheckBox.isChecked())
        
        # Connect the checkbox state change to a function
        self.ScreenedPoissoncheckBox.stateChanged.connect(lambda: self.toggle_widgets(self.ScreenedPoissoncheckBox, [self.ScreenedPoissonItertextEdit]))
        
        self.RemoveIslandscheckBox = self.findChild(QCheckBox, 'RemoveIslandscheckBox')
        
        # Set up Regular inputs
        self.VolumnLengthlineEdit = self.findChild(QLineEdit, 'VolumnLengthlineEdit')
        self.VolumnLengthlineEdit.setValidator(int_validator)
        
        self.VolumnNumberlineEdit = self.findChild(QLineEdit, 'VolumnNumberlineEdit')
        self.VolumnNumberlineEdit.setValidator(int_validator)
        
        # Set up Corners inputs
        self.VolumnLengthCornerlineEdit = self.findChild(QLineEdit, 'VolumnLengthCornerlineEdit')
        self.VolumnLengthCornerlineEdit.setValidator(int_validator)
        
        # Create delete button
        self.AddCornerButton = self.findChild(QPushButton, 'AddCornerButton')
        self.AddCornerButton.clicked.connect(lambda: self.add_manual_entry(self.CornerlineEdit,self.CornertableWidget))
        
        # Set up Manual Name
        self.CornerlineEdit = self.findChild(QLineEdit, 'CornerlineEdit')
        self.CornerlineEdit.setPlaceholderText("x_coord., y_coord., z_coord. (voxel)")
        # Regular expression for three integers separated by commas (spaces allowed)
        regex = QRegularExpression(r"^\d+,\d+,\d+$")
        validator = QRegularExpressionValidator(regex)
        self.CornerlineEdit.setValidator(validator)
        
        self.FindCornerButton = self.findChild(QPushButton, 'FindCornerButton')
        self.FindCornerButton.clicked.connect(self.add_corner_data)
        
        self.CornertableWidget = self.findChild(QTableWidget, 'CornertableWidget')
        self.CornertableWidget.setColumnCount(3)
        self.CornertableWidget.setHorizontalHeaderLabels(["x coord.", "y coord.", "z coord.",])
        self.CornertableWidget.setColumnWidth(0, 100)
        self.CornertableWidget.setColumnWidth(1, 100)
        self.CornertableWidget.setColumnWidth(2, 100)
        self.CornertableWidget.setSelectionBehavior(QTableWidget.SelectRows)  # Select entire rows
        self.CornertableWidget.setSelectionMode(QTableWidget.ExtendedSelection)  # Allow selecting one row at a time
        self.CornertableWidget.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        
        # Create delete button
        self.DeleteCornerButton = self.findChild(QPushButton, 'DeleteCornerButton')
        self.DeleteCornerButton.clicked.connect(lambda: self.delete_selected_rows(self.CornertableWidget))
        
        # Set up Save Options
        self.TiffSavecheckBox = self.findChild(QCheckBox, 'TiffSavecheckBox')
        self.TiffSavePathtextEdit = self.findChild(QLineEdit, 'TiffSavePathtextEdit')
        
        # Initially disable the line edit if the checkbox is not checked
        self.TiffSavePathtextEdit.setEnabled(self.TiffSavecheckBox.isChecked())
        
        # Connect the checkbox state change to a function
        self.TiffSavecheckBox.stateChanged.connect(lambda: self.toggle_widgets(self.TiffSavecheckBox, [self.TiffSavePathtextEdit]))
        
        # Set up Save Options
        self.VoxelSavePathcheckBox = self.findChild(QCheckBox, 'VoxelSavePathcheckBox')
        self.VoxelSavePathtextEdit = self.findChild(QLineEdit, 'VoxelSavePathtextEdit')
        
        # Initially disable the line edit if the checkbox is not checked
        self.VoxelSavePathtextEdit.setEnabled(self.VoxelSavePathcheckBox.isChecked())
        
        # Connect the checkbox state change to a function
        self.VoxelSavePathcheckBox.stateChanged.connect(lambda: self.toggle_widgets(self.VoxelSavePathcheckBox, [self.VoxelSavePathtextEdit]))
        
        # Set up Laplacian Filter
        self.StlSavePathcheckBox = self.findChild(QCheckBox, 'StlSavePathcheckBox')
        self.StlSavePathtextEdit = self.findChild(QLineEdit, 'StlSavePathtextEdit')
        
        # Initially disable the line edit if the checkbox is not checked
        self.StlSavePathtextEdit.setEnabled(self.StlSavePathcheckBox.isChecked())
        
        # Connect the checkbox state change to a function
        self.StlSavePathcheckBox.stateChanged.connect(lambda: self.toggle_widgets(self.StlSavePathcheckBox, [self.StlSavePathtextEdit]))
        
        # Set up Properties flags
        self.PropertySavecheckBox = self.findChild(QCheckBox, 'PropertySavecheckBox')
        self.PropertySavePathtextEdit = self.findChild(QLineEdit, 'PropertySavePathtextEdit')
        self.MinMaxcheckBox = self.findChild(QCheckBox, 'MinMaxcheckBox')
        self.SurfAreacheckBox = self.findChild(QCheckBox, 'SurfAreacheckBox')
        self.ClosedVolumecheckBox = self.findChild(QCheckBox, 'ClosedVolumecheckBox')
        self.VolbyAreacheckBox = self.findChild(QCheckBox, 'VolbyAreacheckBox')
        self.PorositycheckBox = self.findChild(QCheckBox, 'PorositycheckBox')
        self.FiberDiametercheckBox = self.findChild(QCheckBox, 'FiberDiametercheckBox')
        self.FiberDiamSpherelineEdit = self.findChild(QLineEdit, 'FiberDiamSpherelineEdit')
        self.FiberDiamSpherelineEdit.setValidator(float_validator)
        self.PoreDistributioncheckBox = self.findChild(QCheckBox, 'PoreDistributioncheckBox')
        self.PoreDistSpherelineEdit = self.findChild(QLineEdit, 'PoreDistSpherelineEdit')
        self.PoreDistSpherelineEdit.setValidator(float_validator)
        self.FiberAnglecheckBox = self.findChild(QCheckBox, 'FiberAnglecheckBox') 
        self.PlaneAnglecomboBox = self.findChild(QComboBox, 'PlaneAnglecomboBox')
        self.FiberLengthcheckBox = self.findChild(QCheckBox, 'FiberLengthcheckBox')
        
        initialStat = self.PropertySavecheckBox.isChecked()
        
        # Initially disable the line edit if the checkbox is not checked
        self.PropertySavePathtextEdit.setEnabled(initialStat)
        self.MinMaxcheckBox.setEnabled(initialStat)
        self.SurfAreacheckBox.setEnabled(initialStat)
        self.ClosedVolumecheckBox.setEnabled(initialStat)
        self.VolbyAreacheckBox.setEnabled(initialStat)
        self.PorositycheckBox.setEnabled(initialStat)
        self.FiberDiametercheckBox.setEnabled(initialStat)
        self.FiberDiamSpherelineEdit.setEnabled(initialStat)
        self.PoreDistributioncheckBox.setEnabled(initialStat)
        self.PoreDistSpherelineEdit.setEnabled(initialStat)
        self.FiberAnglecheckBox.setEnabled(initialStat)
        self.PlaneAnglecomboBox.setEnabled(initialStat)
        self.FiberLengthcheckBox.setEnabled(initialStat)
        
        self.FiberDiamSpherelineEdit.setEnabled(self.FiberDiametercheckBox.isChecked())
        self.FiberDiametercheckBox.stateChanged.connect(lambda: self.toggle_widgets(self.FiberDiametercheckBox,
                                                                                   [self.FiberDiamSpherelineEdit]))
        
        self.PoreDistSpherelineEdit.setEnabled(self.PoreDistributioncheckBox.isChecked())
        self.PoreDistributioncheckBox.stateChanged.connect(lambda: self.toggle_widgets(self.PoreDistributioncheckBox,
                                                                                   [self.PoreDistSpherelineEdit]))
        
        self.PlaneAnglecomboBox.setEnabled(self.FiberAnglecheckBox.isChecked())
        self.FiberAnglecheckBox.stateChanged.connect(lambda: self.toggle_widgets(self.FiberAnglecheckBox,
                                                                                   [self.PlaneAnglecomboBox]))
        
        # Connect the checkbox state change to a function
        self.PropertySavecheckBox.stateChanged.connect(lambda: self.toggle_widgets(self.PropertySavecheckBox,
                                                                                   [self.PropertySavePathtextEdit,
                                                                                    self.MinMaxcheckBox,
                                                                                    self.SurfAreacheckBox,
                                                                                    self.ClosedVolumecheckBox,
                                                                                    self.VolbyAreacheckBox,
                                                                                    self.PorositycheckBox,
                                                                                    self.FiberDiametercheckBox,
                                                                                    self.FiberDiamSpherelineEdit,
                                                                                    self.PoreDistributioncheckBox,
                                                                                    self.PoreDistSpherelineEdit,
                                                                                    self.FiberAnglecheckBox,
                                                                                    self.FiberLengthcheckBox,
                                                                                    self.PlaneAnglecomboBox])
                                                       )
        self.SelectAllpushButton = self.findChild(QPushButton, 'SelectAllpushButton')
        self.SelectAllpushButton.clicked.connect(self.select_all_properties)
        
        self.UnselectAllpushButton = self.findChild(QPushButton, 'UnselectAllpushButton')
        self.UnselectAllpushButton.clicked.connect(self.unselect_all_properties)
        
        # Set up Run button
        self.RunpushButton = self.findChild(QPushButton, 'RunpushButton')
        self.RunpushButton.clicked.connect(self.run_voxel2stl)
        
        # Create Save Settings Button
        self.SaveSettingsButton = self.findChild(QPushButton, 'SaveSettingspushButton')
        self.SaveSettingsButton.clicked.connect(self.save_settings)

        # Create Load Settings Button
        self.LoadSettingsButton = self.findChild(QPushButton, 'LoadSettingspushButton')
        self.LoadSettingsButton.clicked.connect(self.load_settings)
        
        self.image_data = None
        self.segmentation_mask = None
        self.current_slice = 0
        self.current_plane = "XY"
        
        # Load TIFF to segment
        self.load_button = self.findChild(QPushButton, 'LoadTiffSegmentationpushButton')
        self.load_button.clicked.connect(self.load_tiff)
        
        self.VoxelSizeX = self.findChild(QLineEdit, "VoxelSizeX")
        self.VoxelSizeY = self.findChild(QLineEdit, "VoxelSizeY")
        self.VoxelSizeZ = self.findChild(QLineEdit, "VoxelSizeZ")
        
        self.VoxelSizeX.setValidator(int_validator)
        self.VoxelSizeY.setValidator(int_validator)
        self.VoxelSizeZ.setValidator(int_validator)
        
        self.file_labelSegmentation = self.findChild(QLabel, 'fileNameSegmentationlabel')
        
        self.slider = self.findChild(QSlider, 'CurrentPlanehorizontalSlider')
        self.slider.setMinimum(0)
        self.slider.valueChanged.connect(self.update_slice)
        
        self.slice_label = self.findChild(QLabel, 'currentPlanelabel')
        
        self.figure, self.ax = plt.subplots()
        self.canvas = FigureCanvas(self.figure)
        
        # Ensure canvas resizes dynamically
        self.canvas.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        self.canvas.updateGeometry()
    
        self.graphics_view = self.findChild(QGraphicsView, 'TiffViewgraphicsView')

        # Add Matplotlib canvas to the UI
        layout = QVBoxLayout(self.graphics_view)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.addWidget(self.canvas)
        self.graphics_view.setLayout(layout)
        
        # Update histogram view
        self.update_histogram()
    
        self.plane_selector = self.findChild(QComboBox, 'GreyviewPlanecomboBox')
        self.plane_selector.currentTextChanged.connect(self.change_plane)
        
        # Create a new Matplotlib figure and canvas for the histogram
        self.hist_figure, self.hist_ax = plt.subplots()
        self.hist_canvas = FigureCanvas(self.hist_figure)
    
        # Ensure dynamic resizing
        self.hist_canvas.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        self.hist_canvas.updateGeometry()
    
        # Find the QGraphicsView in Qt Designer
        self.hist_view = self.findChild(QGraphicsView, 'GreyscaleHistogramgraphicsView')
    
        # Add the Matplotlib canvas to the UI
        hist_layout = QVBoxLayout(self.hist_view)
        hist_layout.setContentsMargins(0, 0, 0, 0)
        hist_layout.addWidget(self.hist_canvas)
        self.hist_view.setLayout(hist_layout)
        
        self.GreyScaleSelectioncomboBox = self.findChild(QComboBox, 'GreyScaleSelectioncomboBox') 
        
        self.minthreshold = ''
        self.minthreshold = ''
        self.porosity = 1.0
        
        self.Porositylabel = self.findChild(QLabel, 'Porositylabel')
        
        # Find buttons by object name from the UI file
        self.btnOtsu = self.findChild(QPushButton, "OtsupushButton")
        self.btnAdaptive = self.findChild(QPushButton, "AdaptivepushButton")
        self.BlocksizelineEdit = self.findChild(QLineEdit, "BlocksizelineEdit")
        self.BlocksizelineEdit.setValidator(int_validator)
        self.btnLi = self.findChild(QPushButton, "LipushButton")
        self.btnYen = self.findChild(QPushButton, "YenpushButton")
        self.btnIsodata = self.findChild(QPushButton, "IsodatapushButton")
        self.btnTriangle = self.findChild(QPushButton, "TrianglepushButton")
        self.btnManual = self.findChild(QPushButton, "manualThresholdingpushButton")
        self.minManual = self.findChild(QLineEdit, "MinrthresholdinglineEdit")
        self.minManual.setValidator(int_validator)
        self.maxManual = self.findChild(QLineEdit, "MaxrthresholdinglineEdit")
        self.maxManual.setValidator(int_validator)
        
        # Connect buttons to the segmentation function
        self.btnOtsu.clicked.connect(lambda: self.run_segmentation("Otsu"))
        self.btnAdaptive.clicked.connect(lambda: self.run_segmentation("Adaptive"))
        self.btnLi.clicked.connect(lambda: self.run_segmentation("Li"))
        self.btnYen.clicked.connect(lambda: self.run_segmentation("Yen"))
        self.btnIsodata.clicked.connect(lambda: self.run_segmentation("Isodata"))
        self.btnTriangle.clicked.connect(lambda: self.run_segmentation("Triangle"))
        self.btnManual.clicked.connect(lambda: self.run_segmentation("Manual"))
        
        # Initialize cropping coordinates
        self.xmin, self.xmax = None, None
        self.ymin, self.ymax = None, None
        self.zmin, self.zmax = None, None
        
        # Ensure they have valid values if None
        self.validate_crop_coords()
        
        self.xmin_input = self.findChild(QLineEdit, "XminCroppinglineEdit")
        self.xmax_input = self.findChild(QLineEdit, "XmaxCroppinglineEdit")
        self.ymin_input = self.findChild(QLineEdit, "YminCroppinglineEdit")
        self.ymax_input = self.findChild(QLineEdit, "YmaxCroppinglineEdit")
        self.zmin_input = self.findChild(QLineEdit, "ZminCroppinglineEdit")
        self.zmax_input = self.findChild(QLineEdit, "ZmaxCroppinglineEdit")
        
        self.xmin_input.textChanged.connect(self.update_crop_from_text)
        self.xmax_input.textChanged.connect(self.update_crop_from_text)
        self.ymin_input.textChanged.connect(self.update_crop_from_text)
        self.ymax_input.textChanged.connect(self.update_crop_from_text)
        self.zmin_input.textChanged.connect(self.update_crop_from_text)
        self.zmax_input.textChanged.connect(self.update_crop_from_text)
        
        self.cropTiffpushButton = self.findChild(QPushButton, "cropTiffpushButton")
        self.cropTiffpushButton.clicked.connect(self.crop_image)
        
        self.volumeRenderingpushButton = self.findChild(QPushButton, "volumeRenderingSegmentationpushButton")
        self.volumeRenderingpushButton.clicked.connect(self.show_voxel_rendering)
        
        self.SaveTiffSegmentationpushButton = self.findChild(QPushButton, "SaveTiffSegmentationpushButton")
        self.SaveTiffSegmentationpushButton.clicked.connect(self.save_tiff_segmentation)
        
        self.show()

    def closeEvent(self, event):
        if hasattr(self, "rect_selector"):
            self.rect_selector.set_active(False)
        for canvas_name in ("canvas", "hist_canvas"):
            canvas = getattr(self, canvas_name, None)
            if canvas is not None:
                canvas._draw_pending = False
                canvas.close()
        for figure_name in ("figure", "hist_figure"):
            figure = getattr(self, figure_name, None)
            if figure is not None:
                plt.close(figure)
        event.accept()
    
    def save_tiff_segmentation(self):
        if hasattr(self, "segmentation_mask") and np.sum(self.segmentation_mask) != 0 and self.segmentation_mask is not None:
            options = QFileDialog.Options()
            file_name, _ = QFileDialog.getSaveFileName(self, "Save Segmentation", "", "TIFF Files (*.tif);;All Files (*)", options=options)
            if file_name:
                tiff.imwrite(file_name, self.segmentation_mask.astype(np.uint16),imagej=True) 
                print(f"Segmentation saved as {file_name}")
        else:
            QMessageBox.warning(self, "No Data", "Please segment an image first.")
        
    def show_voxel_rendering(self):
        if hasattr(self, 'segmentation_mask') and np.sum(self.segmentation_mask) != 0 and self.segmentation_mask is not None:
            self.voxel_window = VoxelRenderingWindow(self.segmentation_mask, self.VoxelSizeX.text(), self.VoxelSizeY.text(), self.VoxelSizeZ.text())
            self.voxel_window.show()
        else:
            QMessageBox.warning(self, "No Data", "Please segment an image first.")
        
    def open_file_dialog(self):
        options = QFileDialog.Options()
        file_paths, _ = QFileDialog.getOpenFileNames(
            self,  # Use self as parent
            "Select Files", 
            "",  
            "TIFF or DAT (*.tif *.tiff *.dat);;TIFF (*.tif *.tiff);; DAT (*.dat)", 
            options=options
        )
        
        if file_paths:
            display_text = f"Selected {len(file_paths)} file(s):\n" + "\n".join(file_paths[:3])
            if len(file_paths) > 3:
                display_text += "\n..."
            # self.label1.setText(display_text)
            print("Selected files:", file_paths)
            
            # Populate the table
            self.populate_table(file_paths)
            
    def populate_table(self, file_paths):
        current_row_count = self.tableWidget.rowCount()
        self.tableWidget.setRowCount(current_row_count + len(file_paths))
        
        script_dir = os.path.realpath(os.getcwd())
        
        for i, file in enumerate(file_paths):
            row = current_row_count + i
            
            file_path = os.path.abspath(file)  # Get absolute path
            if os.path.dirname(file_path) == script_dir:
                display_name = os.path.basename(file)  # Use only file name
            else:
                display_name = file_path  # Use full path
            # Add file name to first column
            self.tableWidget.setItem(row, 0, QTableWidgetItem(display_name))

            # Add editable text box to second column (default empty)
            self.tableWidget.setItem(row, 1, QTableWidgetItem("1.0"))

        # Resize to fit the number of files
        self.tableWidget.resizeRowsToContents()
    
    def add_corner_data(self):
        # Open file dialog to select .txt file
        file, _ = QFileDialog.getOpenFileName(self, "Open Corner Data File", "", "Text Files (*.txt)")

        if file:
            with open(file, 'r') as f:
                # Read each line, parse the numbers and add them to the table
                for line in f:
                    # Split the line into values
                    values = line.strip().split('\t')
                    if len(values) == 3:  # Ensure it has exactly 3 values
                        row_position = self.CornertableWidget.rowCount()
                        self.CornertableWidget.insertRow(row_position)
                        for col, value in enumerate(values):
                            self.CornertableWidget.setItem(row_position, col, QTableWidgetItem(value))
                            
    def add_manual_entry(self, manualText, table):
        entry = manualText.text().strip()
        if entry:
            row = table.rowCount()
            table.insertRow(row)
            if table == self.tableWidget:
                table.setItem(row, 0, QTableWidgetItem(entry))
                table.setItem(row, 1, QTableWidgetItem("1.0"))
            if table == self.CornertableWidget:
                entry = entry.replace(" ", "")
                entry = entry.split(',')
                table.setItem(row, 0, QTableWidgetItem(entry[0]))
                table.setItem(row, 1, QTableWidgetItem(entry[1]))
                table.setItem(row, 2, QTableWidgetItem(entry[2]))
            manualText.clear()
            
    def delete_selected_rows(self, table):
        selected_rows = sorted(set(index.row() for index in table.selectedIndexes()), reverse=True)

        for row in selected_rows:
            table.removeRow(row)
    
    def toggle_widgets(self, checkBox, widgets):
        """
        Dynamically enable/disable widgets based on the state of the primary checkbox.

        :param widget_names: A list of widget object names (strings) to enable/disable
        """

        # Iterate through the widget names list
        for widget in widgets:
            if widget is None:
                print(f"Error: Could not find widget with name {widget}")
                continue  # Skip to the next widget if one is not found
                
            elif widget == self.FiberDiamSpherelineEdit and checkBox.isChecked():
                widget.setEnabled(self.FiberDiametercheckBox.isChecked())
            elif widget == self.FiberDiamSpherelineEdit and not checkBox.isChecked():
                widget.setEnabled(False)
                
            elif widget == self.PoreDistSpherelineEdit and checkBox.isChecked():
                widget.setEnabled(self.PoreDistributioncheckBox.isChecked())
            elif widget == self.PoreDistSpherelineEdit and not checkBox.isChecked():
                widget.setEnabled(False)
            elif checkBox == self.LaplaciancheckBox and self.LaplaciancheckBox.isChecked():
                self.ScreenedPoissoncheckBox.setChecked(False)
                widget.setEnabled(checkBox.isChecked())
            elif checkBox == self.ScreenedPoissoncheckBox and self.ScreenedPoissoncheckBox.isChecked():
                self.LaplaciancheckBox.setChecked(False)
                widget.setEnabled(checkBox.isChecked())
            elif widget == self.PlaneAnglecomboBox and checkBox.isChecked():
                widget.setEnabled(self.FiberAnglecheckBox.isChecked())
            else:
                # Enable or disable the widget based on the checkbox state
                widget.setEnabled(checkBox.isChecked())
    
    def select_all_properties(self):
        """Select all property checkboxes."""
        self.MinMaxcheckBox.setChecked(True)
        self.SurfAreacheckBox.setChecked(True)
        self.ClosedVolumecheckBox.setChecked(True)
        self.VolbyAreacheckBox.setChecked(True)
        self.PorositycheckBox.setChecked(True)
        self.FiberDiametercheckBox.setChecked(True)
        self.PoreDistributioncheckBox.setChecked(True)
        self.FiberAnglecheckBox.setChecked(True)
        self.FiberLengthcheckBox.setChecked(True)
    
    def unselect_all_properties(self):
        """Unselect all property checkboxes."""
        self.MinMaxcheckBox.setChecked(False)
        self.SurfAreacheckBox.setChecked(False)
        self.ClosedVolumecheckBox.setChecked(False)
        self.VolbyAreacheckBox.setChecked(False)
        self.PorositycheckBox.setChecked(False)
        self.FiberDiametercheckBox.setChecked(False)
        self.PoreDistributioncheckBox.setChecked(False)
        self.FiberAnglecheckBox.setChecked(False)
        self.FiberLengthcheckBox.setChecked(False)
    
    def save_settings(self):
        options = QFileDialog.Options()
        file_path, _ = QFileDialog.getSaveFileName(self, "Save Settings", "", "JSON Files (*.json);;All Files (*)", options=options)
        
        if file_path:
            settings = {
                'fileNameTable': self.get_table_data(self.tableWidget),
                'cornerTable': self.get_table_data(self.CornertableWidget),
                'TiffSavePath': self.TiffSavePathtextEdit.text(),
                'VoxelSavePath': self.VoxelSavePathtextEdit.text(),
                'StlSavePath': self.StlSavePathtextEdit.text(),
                'PropertySavePath': self.PropertySavePathtextEdit.text(),
                'PropertySaveFlags': {
                    'MinMax': self.MinMaxcheckBox.isChecked(),
                    'SurfArea': self.SurfAreacheckBox.isChecked(),
                    'ClosedVolume': self.ClosedVolumecheckBox.isChecked(),
                    'VolbyArea': self.VolbyAreacheckBox.isChecked(),
                    'Porosity': self.PorositycheckBox.isChecked(),
                    'FiberDiameter': self.FiberDiametercheckBox.isChecked(),
                    'FiberDiamSphere': self.FiberDiamSpherelineEdit.text(),
                    'PoreDistribution': self.PoreDistributioncheckBox.isChecked(),
                    'PoreDistriDiamSphere': self.PoreDistSpherelineEdit.text(),
                    'FiberLength': self.FiberLengthcheckBox.isChecked(),
                    'FiberAngle': self.FiberAnglecheckBox.isChecked(),
                    'FiberAnglePlane': self.PlaneAnglecomboBox.currentText(),
                },
                
                'Laplacian': self.LaplaciancheckBox.isChecked(),
                'LaplacianIter': self.LaplacianItertextEdit.text(),
                'ScreenedPoisson': self.ScreenedPoissoncheckBox.isChecked(), 

                'ScreenedPoissonIter': self.ScreenedPoissonItertextEdit.text(),
                'RemoveIslands': self.RemoveIslandscheckBox.isChecked(),
                'VoxelLength': self.VolumnLengthlineEdit.text(),
                'VolumeLength': self.VolumnNumberlineEdit.text(),
                'VolumeLengthCorner': self.VolumnLengthCornerlineEdit.text(),
                'TiffSave': self.TiffSavecheckBox.isChecked(),
                'VoxelSave': self.VoxelSavePathcheckBox.isChecked(),
                'StlSave': self.StlSavePathcheckBox.isChecked(),
                'PropertySave': self.PropertySavecheckBox.isChecked(),
                
            }

            try:
                settings['workflowConfig'] = build_workflow_config(self._workflow_run_state())
            except GuiAdapterError as exc:
                settings['workflowConfigExportError'] = str(exc)

            with open(file_path, 'w') as f:
                json.dump(settings, f, indent=4)

    def get_table_data(self, table):
        data = []
        for row in range(table.rowCount()):
            row_data = []
            for col in range(table.columnCount()):
                item = table.item(row, col)
                row_data.append(item.text() if item else "")
            data.append(row_data)
        return data
    
    def load_settings(self):
        options = QFileDialog.Options()
        file_path, _ = QFileDialog.getOpenFileName(self, "Load Settings", "", "JSON Files (*.json);;All Files (*)", options=options)
        
        if file_path:
            with open(file_path, 'r') as f:
                settings = json.load(f)
            if "fileNameTable" not in settings and ("workflowConfig" in settings or "input" in settings or "inputs" in settings):
                settings = gui_settings_from_workflow_config(settings, base_dir=Path(file_path).parent)

            self.load_table_data(self.tableWidget, settings.get('fileNameTable', []))
            self.load_table_data(self.CornertableWidget, settings.get('cornerTable', []))

            self.TiffSavePathtextEdit.setText(settings.get('TiffSavePath', ''))
            self.VoxelSavePathtextEdit.setText(settings.get('VoxelSavePath', ''))
            self.StlSavePathtextEdit.setText(settings.get('StlSavePath', ''))
            self.PropertySavePathtextEdit.setText(settings.get('PropertySavePath', ''))

            self.set_checkbox_state(self.MinMaxcheckBox, settings['PropertySaveFlags'].get('MinMax', False))
            self.set_checkbox_state(self.SurfAreacheckBox, settings['PropertySaveFlags'].get('SurfArea', False))
            self.set_checkbox_state(self.ClosedVolumecheckBox, settings['PropertySaveFlags'].get('ClosedVolume', False))
            self.set_checkbox_state(self.VolbyAreacheckBox, settings['PropertySaveFlags'].get('VolbyArea', False))
            self.set_checkbox_state(self.PorositycheckBox, settings['PropertySaveFlags'].get('Porosity', False))
            self.set_checkbox_state(self.FiberDiametercheckBox, settings['PropertySaveFlags'].get('FiberDiameter', False))
            self.FiberDiamSpherelineEdit.setText(settings['PropertySaveFlags'].get('FiberDiamSphere', ''))
            self.set_checkbox_state(self.PoreDistributioncheckBox, settings['PropertySaveFlags'].get('PoreDistribution', False))
            self.PoreDistSpherelineEdit.setText(settings['PropertySaveFlags'].get('PoreDistriDiamSphere', ''))
            self.set_checkbox_state(self.FiberLengthcheckBox, settings['PropertySaveFlags'].get('FiberLength', False))
            self.set_checkbox_state(self.FiberAnglecheckBox, settings['PropertySaveFlags'].get('FiberAngle', False))
            self.PlaneAnglecomboBox.setCurrentText(settings['PropertySaveFlags'].get('FiberAnglePlane', ''))

            self.set_checkbox_state(self.LaplaciancheckBox, settings.get('Laplacian', False))
            self.LaplacianItertextEdit.setText(settings.get('LaplacianIter', ''))
            self.set_checkbox_state(self.ScreenedPoissoncheckBox, settings.get('ScreenedPoisson', False))
            self.ScreenedPoissonItertextEdit.setText(settings.get('ScreenedPoissonIter', ''))
            self.set_checkbox_state(self.RemoveIslandscheckBox, settings.get('RemoveIslands', False))
            self.VolumnLengthlineEdit.setText(settings.get('VoxelLength', ''))
            self.VolumnNumberlineEdit.setText(settings.get('VolumeLength', ''))
            self.VolumnLengthCornerlineEdit.setText(settings.get('VolumeLengthCorner', ''))
            self.set_checkbox_state(self.TiffSavecheckBox, settings.get('TiffSave', False))
            self.set_checkbox_state(self.VoxelSavePathcheckBox, settings.get('VoxelSave', False))
            self.set_checkbox_state(self.StlSavePathcheckBox, settings.get('StlSave', False))
            self.set_checkbox_state(self.PropertySavecheckBox, settings.get('PropertySave', False))

    def load_table_data(self, table, data):
        # Clear the existing data in the table
        table.setRowCount(0)
        
        for row_data in data:
            row_position = table.rowCount()
            table.insertRow(row_position)
            for col, value in enumerate(row_data):
                table.setItem(row_position, col, QTableWidgetItem(value))
        
        # Resize to fit the number of files
        self.tableWidget.resizeRowsToContents()

    def set_checkbox_state(self, checkbox, state):
        checkbox.setChecked(state)
    
    def load_tiff(self):
        file_path, _ = QFileDialog.getOpenFileName(self, "Open TIFF", "", "TIFF Files (*.tif *.tiff)")
        if file_path:
            self.image_data = tiff.imread(file_path)
            self.segmentation_mask = np.zeros_like(self.image_data, dtype=bool)
            self.slider.setMaximum(self.image_data.shape[0] - 1)
            self.current_slice = 0
            self.minthreshold = ''
            self.minthreshold = ''
            self.porosity = 1.0
            self.update_view()
            self.update_histogram()
            
            # Extract the filename from the full path and update the label
            file_name = os.path.basename(file_path)
            self.file_labelSegmentation.setText(f"Loaded: {file_name}")
            self.slice_label.setText(f"Slice: {self.current_slice+1}")
            
            

    def change_plane(self, plane):
        self.current_plane = plane
        self.slider.setMaximum(self.image_data.shape[0] - 1 if plane == "XY" else self.image_data.shape[1] - 1)
        self.update_view()
        self.update_rectangles()

    def update_slice(self, value):
        self.current_slice = value
        self.slice_label.setText(f"Slice: {self.current_slice+1}")
        self.update_view()

    def get_slice(self):
        if self.current_plane == "XY":
            return self.image_data[self.current_slice, :, :], self.segmentation_mask[self.current_slice, :, :]
        elif self.current_plane == "XZ":
            return self.image_data[:, self.current_slice, :], self.segmentation_mask[:, self.current_slice, :]
        else:
            return self.image_data[:, :, self.current_slice], self.segmentation_mask[:, :, self.current_slice]

    def update_view(self):
        if self.image_data is None:
            return
        plt.rcParams['font.size'] = 5
        
        raw_slice, seg_slice = self.get_slice()
    
        # Clear the figure and remove extra whitespace
        self.ax.cla()
        self.figure.subplots_adjust(left=0.2, right=.95, top=.97, bottom=0.18)  # Fit image tightly
    
        # Show raw image with correct aspect ratio
        self.ax.imshow(raw_slice, cmap="gray", )
    
        # Create an RGBA version of seg_slice where False values are fully transparent
        overlay = np.zeros((*seg_slice.shape, 4))  # Initialize an RGBA image (H, W, 4)
        overlay[..., 2] = 1.0  # Set blue channel to 1.0 (Blues colormap)
        overlay[..., 3] = seg_slice.astype(float) * 0.5  # Alpha (transparency), scaled by 0.5
    
        # Overlay segmentation mask with transparency
        self.ax.imshow(overlay)
    
        # Set axis labels and remove ticks
        self.ax.set_xlabel("X-axis", labelpad=2)
        self.ax.set_ylabel("Y-axis", labelpad=1)
        
        # Initialize or update the rectangle selector
        if not hasattr(self, "rect_selector"):
            self.rect_selector = RectangleSelector(self.ax, self.on_select, interactive=True,
                                                       props=dict(facecolor='none', edgecolor='red', linewidth=2))
        else:
            self.rect_selector.set_active(True)
        
        self.figure.tight_layout()
        
        # Refresh the canvas
        self.canvas.draw()
        

    def run_segmentation(self, method):
        if self.image_data is None:
            return
        self.thread = SegmentationThread(self.image_data, method, self.GreyScaleSelectioncomboBox.currentIndex(), Blocksize=self.BlocksizelineEdit, minManual=self.minManual.text(),maxManual=self.maxManual.text())
        self.thread.finished.connect(self.on_segmentation_done)
        self.thread.start()

    def on_segmentation_done(self, segmentation_mask, minthreshold, maxthreshold,porosity):
        self.segmentation_mask = segmentation_mask
        self.minthreshold = minthreshold
        self.maxthreshold = maxthreshold
        self.porosity = porosity
        self.update_view()
        self.update_histogram()
        
    def update_histogram(self):
        """Compute and display the grayscale histogram of the current slice."""
        if self.image_data is None:
            return
        plt.rcParams['font.size'] = 5
    
        # Clear previous histogram
        self.hist_ax.clear()
        
        self.hist_figure.subplots_adjust(left=0, right=1, top=1, bottom=0)
        
        # Compute histogram (256 bins for grayscale values)
        self.hist_ax.hist(self.image_data.ravel(), bins=300, range=(0, 65536), color='black')
        
        if self.minthreshold != '' and self.maxthreshold != '':
            print(self.minthreshold,self.maxthreshold)
            # Add vertical lines for threshold values
            self.hist_ax.axvline(int(self.minthreshold), color='red', linestyle='--', linewidth=2, label="Min Threshold")
            self.hist_ax.axvline(int(self.maxthreshold), color='red', linestyle='--', linewidth=2, label="Max Threshold")
        
    
        # Set labels
        # self.hist_ax.set_xlabel("Pixel Int.")
        # self.hist_ax.set_ylabel("Freq.")
    
        # Remove unnecessary grid/ticks
        self.hist_ax.set_xticks(np.linspace(0, np.max(self.image_data), num=7))  # Tick marks at 0, 50, 100, ...
        self.hist_ax.set_yticks([])  # Hide Y ticks for a cleaner look
        
        self.hist_figure.tight_layout()
        
        
        # Refresh canvas
        self.hist_canvas.draw()
        
        self.Porositylabel.setText(f'Porosity: {self.porosity:.4f}')
    
    def on_select(self, eclick, erelease):
        """Callback when user selects a region. Updates cropping box in all views."""
        
        # # If a rectangle already exists, don't allow new drawing
        # if hasattr(self, 'rect') and self.rect is not None:
        #     return
        
        x1, y1 = int(eclick.xdata), int(eclick.ydata)
        x2, y2 = int(erelease.xdata), int(erelease.ydata)
    
        # Ensure coordinates are sorted correctly
        x1, x2 = sorted([x1, x2])
        y1, y2 = sorted([y1, y2])
    
        # Update appropriate dimensions based on the selected plane
        if self.current_plane == 'XY':
            self.xmin, self.xmax = x1, x2
            self.ymin, self.ymax = y1, y2
    
            # If zmin/zmax are undefined, initialize to full extent
            if self.zmin is None or self.zmax is None:
                self.zmin, self.zmax = 0, self.image_data.shape[0] - 1  
    
        elif self.current_plane == 'XZ':
            self.xmin, self.xmax = x1, x2
            self.zmin, self.zmax = y1, y2  # Z is vertical in this plane
    
            if self.ymin is None or self.ymax is None:
                self.ymin, self.ymax = 0, self.image_data.shape[1] - 1  
    
        elif self.current_plane == 'YZ':
            self.ymin, self.ymax = x1, x2
            self.zmin, self.zmax = y1, y2  
    
            if self.xmin is None or self.xmax is None:
                self.xmin, self.xmax = 0, self.image_data.shape[2] - 1  
    
        # Ensure all coordinates are valid
        self.validate_crop_coords()
    
        # Update UI and rectangle
        self.update_text_inputs()
        self.update_rectangles()
    
        # Disable the rectangle selector after drawing the first one
        self.rect_selector.set_active(False)

    def validate_crop_coords(self):
        """Ensure all cropping coordinates are valid and within dataset bounds."""
        
        if self.image_data is None:
            return
    
        shape = self.image_data.shape  # (Z, Y, X)

        if self.xmin is None or self.xmax is None:
            self.xmin, self.xmax = 0, shape[2] - 1
        if self.ymin is None or self.ymax is None:
            self.ymin, self.ymax = 0, shape[1] - 1
        if self.zmin is None or self.zmax is None:
            self.zmin, self.zmax = 0, shape[0] - 1

        # Ensure sorted values
        self.xmin, self.xmax = sorted([self.xmin, self.xmax])
        self.ymin, self.ymax = sorted([self.ymin, self.ymax])
        self.zmin, self.zmax = sorted([self.zmin, self.zmax])
    
    def update_rectangles(self):
        """Update cropping rectangles in all views based on stored coordinates."""
    
        # Clear previous rectangles
        for patch in self.ax.patches:
            patch.remove()
    
        # Ensure cropping coordinates are valid before drawing
        if self.current_plane == 'XY':
            if None in [self.xmin, self.xmax, self.ymin, self.ymax]:
                return  # Don't update rectangle if any coordinate is None
            rect = plt.Rectangle((self.xmin, self.ymin), self.xmax - self.xmin, self.ymax - self.ymin,
                                 linewidth=2, edgecolor='red', facecolor='none')
    
        elif self.current_plane == 'XZ':
            if None in [self.xmin, self.xmax, self.zmin, self.zmax]:
                return  # Don't update rectangle if any coordinate is None
            rect = plt.Rectangle((self.xmin, self.zmin), self.xmax - self.xmin, self.zmax - self.zmin,
                                 linewidth=2, edgecolor='red', facecolor='none')
    
        elif self.current_plane == 'YZ':
            if None in [self.ymin, self.ymax, self.zmin, self.zmax]:
                return  # Don't update rectangle if any coordinate is None
            rect = plt.Rectangle((self.ymin, self.zmin), self.ymax - self.ymin, self.zmax - self.zmin,
                                 linewidth=2, edgecolor='red', facecolor='none')
    
        self.ax.add_patch(rect)
    
        # Refresh canvas
        self.canvas.draw()

    
    def update_crop_from_text(self):
        """Update rectangle when user manually inputs crop coordinates."""
        try:
            self.xmin = int(self.xmin_input.text())
            self.xmax = int(self.xmax_input.text())
            self.ymin = int(self.ymin_input.text())
            self.ymax = int(self.ymax_input.text())
            self.zmin = int(self.zmin_input.text())
            self.zmax = int(self.zmax_input.text())
    
            self.validate_crop_coords()
            self.update_rectangles()
        except ValueError:
            pass  # Ignore invalid input
        
        # Update text inputs in case user edited them manually
        self.update_text_inputs()
    
    def update_text_inputs(self):
        """Update the text inputs based on the current crop coordinates."""
        if self.xmin is not None and self.xmax is not None:
            self.xmin_input.setText(str(self.xmin))
            self.xmax_input.setText(str(self.xmax))
    
        if self.ymin is not None and self.ymax is not None:
            self.ymin_input.setText(str(self.ymin))
            self.ymax_input.setText(str(self.ymax))
    
        if self.zmin is not None and self.zmax is not None:
            self.zmin_input.setText(str(self.zmin))
            self.zmax_input.setText(str(self.zmax))
    
        # # Debugging: Print values to check if they are being set correctly
        # print(f"Updating text inputs: xmin={self.xmin}, xmax={self.xmax}, ymin={self.ymin}, ymax={self.ymax}, zmin={self.zmin}, zmax={self.zmax}")
    
    def crop_image(self):
        """ Crop the selected region and update the view """
        
        if self.image_data is None:
            return
        
        if hasattr(self, 'xmin') and hasattr(self, 'xmax'):
            self.image_data = self.image_data[self.zmin:self.zmax, self.ymin:self.ymax, self.xmin:self.xmax]
            self.segmentation_mask = self.segmentation_mask[self.zmin:self.zmax, self.ymin:self.ymax, self.xmin:self.xmax]
            
            self.slider.setMaximum(self.image_data.shape[0] - 1)
            self.current_slice = 0
            self.update_view()
            
            self.xmin_input.setText('0')
            self.xmax_input.setText('%i'%self.image_data.shape[2])
            self.ymin_input.setText('0')
            self.ymax_input.setText('%i'%self.image_data.shape[1])
            self.zmin_input.setText('0')
            self.zmax_input.setText('%i'%self.image_data.shape[0])
    
    def run_voxel2stl(self):
        state = self._workflow_run_state()
        try:
            workflow_config = build_workflow_config(state)
        except GuiAdapterError as exc:
            self.show_error_message("Error", str(exc))
            return

        # Close the UI window
        self.close()
        run_workflow_config(workflow_config)

    def _workflow_run_state(self):
        input_rows = []
        for row in range(self.tableWidget.rowCount()):
            file_item = self.tableWidget.item(row, 0)
            voxel_item = self.tableWidget.item(row, 1)
            input_rows.append(
                (
                    file_item.text() if file_item is not None else None,
                    voxel_item.text() if voxel_item is not None else None,
                )
            )

        corner_rows = []
        for row in range(self.CornertableWidget.rowCount()):
            corner_rows.append(
                tuple(
                    item.text() if item is not None else None
                    for item in [
                        self.CornertableWidget.item(row, 0),
                        self.CornertableWidget.item(row, 1),
                        self.CornertableWidget.item(row, 2),
                    ]
                )
            )

        return {
            "input_rows": input_rows,
            "corner_rows": corner_rows,
            "active_tab_index": self.tabWidget.currentIndex(),
            "laplacian": self.LaplaciancheckBox.isChecked(),
            "laplacian_iter": self.LaplacianItertextEdit.text(),
            "screened_poisson": self.ScreenedPoissoncheckBox.isChecked(),
            "screened_poisson_iter": self.ScreenedPoissonItertextEdit.text(),
            "remove_islands": self.RemoveIslandscheckBox.isChecked(),
            "tiff_save": self.TiffSavecheckBox.isChecked(),
            "tiff_path": self.TiffSavePathtextEdit.text(),
            "voxel_save": self.VoxelSavePathcheckBox.isChecked(),
            "voxel_path": self.VoxelSavePathtextEdit.text(),
            "stl_save": self.StlSavePathcheckBox.isChecked(),
            "stl_path": self.StlSavePathtextEdit.text(),
            "property_save": self.PropertySavecheckBox.isChecked(),
            "property_path": self.PropertySavePathtextEdit.text(),
            "min_max": self.MinMaxcheckBox.isChecked(),
            "surf_area": self.SurfAreacheckBox.isChecked(),
            "closed_volume": self.ClosedVolumecheckBox.isChecked(),
            "vol_by_area": self.VolbyAreacheckBox.isChecked(),
            "porosity": self.PorositycheckBox.isChecked(),
            "fiber_diameter": self.FiberDiametercheckBox.isChecked(),
            "fiber_diam_sphere": self.FiberDiamSpherelineEdit.text(),
            "pore_distribution": self.PoreDistributioncheckBox.isChecked(),
            "pore_dist_sphere": self.PoreDistSpherelineEdit.text(),
            "fiber_angle": self.FiberAnglecheckBox.isChecked(),
            "fiber_angle_plane": self.PlaneAnglecomboBox.currentText(),
            "fiber_length": self.FiberLengthcheckBox.isChecked(),
            "regular_volume_length": self.VolumnLengthlineEdit.text(),
            "regular_num_volumes": self.VolumnNumberlineEdit.text(),
            "corner_volume_length": self.VolumnLengthCornerlineEdit.text(),
        }
        
        
    def show_error_message(self, title, message):
        """Displays an error message box."""
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Critical)
        msg.setText(message)
        msg.setWindowTitle(title)
        msg.exec_()

def window():
    app = QApplication(sys.argv)
    app.setAttribute(Qt.AA_EnableHighDpiScaling) # Enable High DPI Scaling 
    app.setAttribute(Qt.AA_UseHighDpiPixmaps)
    app.setStyle("Fusion")
    ui = UI()
    ui.show()
    sys.exit(app.exec_())

if __name__ == "__main__":
    window()
